const RC3_VERSION='1.7-rc3';
const RC3_BACKUP_MIN_PASSWORD=12;
const RC3_CLOUD_MIN_PASSWORD=12;
const RC3_CLOUD_BUCKET='lattes-assist-vaults';
const RC3_CLOUD_SCHEMA='lattes-assist.cloud-vault.v1';
const RC3_CLOUD_PAYLOAD_SCHEMA='lattes-assist.cloud-vault.payload.v1';
const RC3_KDF_ITERATIONS=310000;
const RC3_CHUNK_SIZE=8*1024*1024;

function rc3ActivatePanel(id){
  $$('.nav button[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));
  $$('.panel').forEach(x=>x.classList.toggle('active',x.id===id));
}
function rc3EnsureQueuePanel(){
  if($('#queue'))return;
  const workflow=$('#workflow'),sync=$('#sync'),queueCard=$('#queueList')?.closest('.section.card');
  if(!workflow||!queueCard)return;
  const panel=document.createElement('section');panel.id='queue';panel.className='panel';
  const header=document.createElement('header');header.className='topbar';
  header.innerHTML='<div><div class="eyebrow">Preparação das alterações</div><h2>Fila de atualização</h2><p class="sub">Revise, filtre, reclassifique e remova operações antes de gerar a Atualização Assistida.</p></div><div class="actions" id="queueHeaderActions"></div>';
  panel.appendChild(header);panel.appendChild(queueCard);workflow.parentNode.insertBefore(panel,workflow);
  const actions=header.querySelector('#queueHeaderActions');
  const exportBtn=$('#exportQueue'),clearBtn=$('#clearQueue');if(exportBtn)actions.appendChild(exportBtn);if(clearBtn)actions.appendChild(clearBtn);
  if(sync){
    const h=sync.querySelector('header.topbar');if(h){h.querySelector('.eyebrow')&&(h.querySelector('.eyebrow').textContent='Interoperabilidade');h.querySelector('h2')&&(h.querySelector('h2').textContent='Integrações');h.querySelector('.sub')&&(h.querySelector('.sub').textContent='Conectores de atualização e integração institucional, sem automatizar credenciais da Plataforma Lattes.');}
  }
}
function rc3OrganizeNavigation(){
  const nav=$('.nav');if(!nav)return;rc3EnsureQueuePanel();
  const labels={dashboard:'1. Currículo Lattes (XML)',documents:'2. Documentos e evidências',external:'3. Fontes externas e prospecção',updates:'4. Atualizações DOI',audit:'5. Auditoria',retro:'6. Retrospectiva',timeline:'7. Linha do tempo',identity:'8. Identidade',decision:'9. Decisões',queue:'10. Fila',workflow:'11. Atualização assistida',schema:'12. XSD / XML',diff:'13. Diff XML',sources:'14. Conta, nuvem e backup',sync:'15. Integrações'};
  const groups=[['Entrada e prospecção',['dashboard','documents','external','updates']],['Análise e decisão',['audit','retro','timeline','identity','decision']],['Preparação da atualização',['queue','workflow','schema','diff']],['Conta e sistema',['sources','sync']]];
  const current=$('.nav button.active')?.dataset.panel||'dashboard';nav.innerHTML='';
  const style=document.createElement('style');style.id='rc3NavStyle';style.textContent='.nav .nav-group-label{margin:16px 12px 6px;font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;opacity:.58}.nav .nav-group-label:first-child{margin-top:4px}';document.head.appendChild(style);
  for(const [title,ids] of groups){const g=document.createElement('div');g.className='nav-group-label';g.textContent=title;nav.appendChild(g);for(const id of ids){if(!$('#'+id))continue;const b=document.createElement('button');b.dataset.panel=id;b.textContent=labels[id]||id;b.classList.toggle('active',id===current);b.addEventListener('click',()=>rc3ActivatePanel(id));nav.appendChild(b)}}
  rc3ActivatePanel($('#'+current)?current:'dashboard');
}

async function rc3DeriveKey(passphrase,salt,iterations=RC3_KDF_ITERATIONS){
  const enc=new TextEncoder();const base=await crypto.subtle.importKey('raw',enc.encode(passphrase),'PBKDF2',false,['deriveKey']);
  return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);
}
async function rc3EncryptBytes(bytes,key){const iv=crypto.getRandomValues(new Uint8Array(12));const data=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data);return {iv,bytes:new Uint8Array(cipher)}}
async function rc3DecryptBytes(bytes,key,iv){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,bytes instanceof Uint8Array?bytes:new Uint8Array(bytes));return new Uint8Array(plain)}
function rc3ConcatBytes(parts,total=null){const n=total??parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(n);let off=0;for(const p of parts){out.set(p,off);off+=p.length}return out}
function rc3StrongPass(pass,min){return typeof pass==='string'&&pass.length>=min}

async function rc3EncryptBackup(payload,passphrase){
  const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await rc3DeriveKey(passphrase,salt,RC3_KDF_ITERATIONS),plain=new TextEncoder().encode(JSON.stringify(payload)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);
  return {schema:'lattes-assist.backup.encrypted.v1',createdAt:payload.createdAt,kdf:{name:'PBKDF2',hash:'SHA-256',iterations:RC3_KDF_ITERATIONS,salt:bytesToBase64(salt)},cipher:{name:'AES-GCM',iv:bytesToBase64(iv)},data:bytesToBase64(new Uint8Array(cipher))};
}
async function rc3DecryptBackup(container,passphrase){
  if(container?.schema!=='lattes-assist.backup.encrypted.v1')throw new Error('A RC3 restaura somente backups criptografados.');
  const salt=base64ToBytes(container.kdf?.salt||''),iv=base64ToBytes(container.cipher?.iv||''),iterations=Number(container.kdf?.iterations)||210000,key=await rc3DeriveKey(passphrase,salt,iterations);
  const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,base64ToBytes(container.data||''));return JSON.parse(new TextDecoder().decode(plain));
}
async function rc3ApplyPayload(payload,preparedEvidence=null){
  validateBackupPayloadRc2(payload);const incoming=preparedEvidence||prepareEvidenceSnapshotRc2(payload.indexedDB),rollbackDb=await captureEvidenceRollbackRc2(),rollbackStorage=localStorageSnapshot(),rollbackState=cloneSerializableStateRc2(),rollbackRawXml=state.runtime.rawXml||'',rollbackRawXsd=state.runtime.rawXsd||'';
  try{
    await atomicReplaceEvidenceDbRc2(incoming);restoreScopedLocalStorageRc2(payload.localStorage||{});restoreStateSnapshot(payload.state||{});state.runtime.rawXml=payload.session?.rawXml||'';state.runtime.rawXsd=payload.session?.rawXsd||'';save();await loadDocuments();renderAll();renderBackupInfo(payload);
  }catch(err){
    let rollbackError=null;try{await atomicReplaceEvidenceDbRc2(rollbackDb);restoreScopedLocalStorageRc2(rollbackStorage);restoreStateSnapshot(rollbackState);state.runtime.rawXml=rollbackRawXml;state.runtime.rawXsd=rollbackRawXsd;save();await loadDocuments();renderAll();renderBackupInfo()}catch(e){rollbackError=e}
    if(rollbackError)throw new Error('A restauração falhou e o rollback também falhou: '+rollbackError.message);throw new Error('A restauração não foi aplicada; o estado anterior foi recuperado: '+err.message);
  }
}
function rc3RebuildBackupUi(){
  const old=$('#backupExport')?.closest('.section.card');if(!old)return;
  old.innerHTML=`<div class="section-head"><h3>Backup criptografado</h3><span class="small">criptografia obrigatória no dispositivo</span></div><div class="notice">Todos os novos backups são criptografados antes de serem gravados. A senha não é armazenada nem recuperável pelo Lattes Assist. Guarde-a em um gerenciador de senhas.</div><div class="formgrid"><label>Senha do backup<input id="backupPassphrase" type="password" autocomplete="new-password" minlength="${RC3_BACKUP_MIN_PASSWORD}" placeholder="mínimo de ${RC3_BACKUP_MIN_PASSWORD} caracteres"></label><label>Confirmar senha do backup<input id="backupPassphraseConfirm" type="password" autocomplete="new-password" minlength="${RC3_BACKUP_MIN_PASSWORD}" placeholder="redigite a senha"></label><label>Arquivo de backup criptografado<input id="backupImport" type="file" accept="application/json,.json"></label><label>Senha para restaurar<input id="backupRestorePassphrase" type="password" autocomplete="off" minlength="${RC3_BACKUP_MIN_PASSWORD}" placeholder="redigite a senha do backup"></label></div><div class="row" style="margin-top:12px"><button class="btn primary" id="backupExport">Exportar backup criptografado</button><span class="small" id="backupStatus"></span></div><div class="source" style="margin-top:12px"><div><strong>Dados locais atuais</strong><span class="small" id="backupCurrent"></span></div></div><div class="source"><div><strong>Último backup processado nesta sessão</strong><span class="small" id="backupLast"></span></div></div>`;
  $('#backupExport').addEventListener('click',rc3ExportEncryptedBackup);$('#backupImport').addEventListener('change',rc3RestoreEncryptedBackup);renderBackupInfo();
}
async function rc3ExportEncryptedBackup(){
  const p1=$('#backupPassphrase')?.value||'',p2=$('#backupPassphraseConfirm')?.value||'',btn=$('#backupExport');if(!rc3StrongPass(p1,RC3_BACKUP_MIN_PASSWORD))return $('#backupStatus').textContent=`Use uma senha com pelo menos ${RC3_BACKUP_MIN_PASSWORD} caracteres.`;if(p1!==p2)return $('#backupStatus').textContent='As duas senhas do backup não coincidem.';
  btn.disabled=true;$('#backupStatus').textContent='Preparando e criptografando backup integral…';try{const payload=await buildFullBackup();payload.appVersion=RC3_VERSION;const out=await rc3EncryptBackup(payload,p1),date=new Date().toISOString().slice(0,10);downloadBackup(`lattes-assist-backup-${date}.encrypted.json`,out);const s=backupSummary(payload);$('#backupStatus').textContent=`Backup criptografado criado: ${s.documents} documento(s), ${s.files} arquivo(s), ${fmtBytes(s.fileBytes)}.`;renderBackupInfo(payload)}catch(e){$('#backupStatus').textContent='Falha no backup: '+e.message}finally{btn.disabled=false;$('#backupPassphrase').value='';$('#backupPassphraseConfirm').value=''}}
async function rc3RestoreEncryptedBackup(e){
  const file=e.target.files?.[0];if(!file)return;const pass=$('#backupRestorePassphrase')?.value||'';try{if(!rc3StrongPass(pass,1))throw new Error('Redigite a senha do backup antes de restaurar.');let container;try{container=JSON.parse(await file.text())}catch{throw new Error('O arquivo selecionado não contém JSON válido.')}if(container.schema!=='lattes-assist.backup.encrypted.v1')throw new Error('A RC3 aceita restauração somente de backup criptografado.');let payload;try{payload=await rc3DecryptBackup(container,pass)}catch{throw new Error('Não foi possível descriptografar o backup. Verifique a senha redigitada.')}validateBackupPayloadRc2(payload);const s=backupSummary(payload);if(!confirm(`Restaurar o backup criptografado substituirá os dados locais atuais.\n\n${s.documents} documento(s) · ${s.files} arquivo(s) · ${s.queue} operação(ões) na fila.\n\nContinuar?`))return;$('#backupStatus').textContent='Restaurando backup criptografado em modo transacional…';await rc3ApplyPayload(payload);$('#backupStatus').textContent='Restauração criptografada concluída com segurança.'}catch(err){$('#backupStatus').textContent='Falha na restauração: '+err.message}finally{e.target.value='';if($('#backupRestorePassphrase'))$('#backupRestorePassphrase').value=''}}

function rc3VaultPath(vaultId,name){return `${cloudSession.user.id}/${vaultId}/${name}`}
async function rc3UploadObject(client,path,bytes){const blob=bytes instanceof Blob?bytes:new Blob([bytes],{type:'application/octet-stream'});const {error}=await client.storage.from(RC3_CLOUD_BUCKET).upload(path,blob,{contentType:'application/octet-stream',cacheControl:'0',upsert:false});if(error)throw error}
async function rc3DownloadBytes(client,path){const {data,error}=await client.storage.from(RC3_CLOUD_BUCKET).download(path);if(error)throw error;return new Uint8Array(await data.arrayBuffer())}
async function rc3DeleteVault(client,vaultId){if(!vaultId||!cloudSession?.user)return;const prefix=`${cloudSession.user.id}/${vaultId}`;const {data,error}=await client.storage.from(RC3_CLOUD_BUCKET).list(prefix,{limit:1000});if(error)return;const paths=(data||[]).map(x=>`${prefix}/${x.name}`);if(paths.length)await client.storage.from(RC3_CLOUD_BUCKET).remove(paths)}
async function rc3EncryptAndUploadChunks(client,key,vaultId,prefix,bytes){const out=[];for(let off=0,i=0;off<bytes.length;off+=RC3_CHUNK_SIZE,i++){const part=bytes.subarray(off,Math.min(bytes.length,off+RC3_CHUNK_SIZE)),enc=await rc3EncryptBytes(part,key),name=`${prefix}${String(i).padStart(5,'0')}.bin`,path=rc3VaultPath(vaultId,name);await rc3UploadObject(client,path,enc.bytes);out.push({path,iv:bytesToBase64(enc.iv),plainSize:part.length,cipherSize:enc.bytes.length})}return out}
async function rc3BuildAndUploadVault(client,passphrase,vaultId){
  const salt=crypto.getRandomValues(new Uint8Array(16)),key=await rc3DeriveKey(passphrase,salt),docs=await dbAll(),fileDescriptors=[];let fileCounter=0,totalPlainBytes=0;
  for(const d of docs){const blob=await dbGetBlob(d.id);if(!blob)continue;const bytes=new Uint8Array(await blob.arrayBuffer());totalPlainBytes+=bytes.length;const chunks=await rc3EncryptAndUploadChunks(client,key,vaultId,`f${String(fileCounter++).padStart(5,'0')}-`,bytes);fileDescriptors.push({id:d.id,type:blob.type||'application/octet-stream',size:blob.size,chunks})}
  const manifest={schema:RC3_CLOUD_PAYLOAD_SCHEMA,createdAt:new Date().toISOString(),appVersion:RC3_VERSION,state:serializableState(),localStorage:localStorageSnapshot(),session:{rawXml:state.runtime.rawXml||'',rawXsd:state.runtime.rawXsd||''},indexedDB:{documents:docs,files:fileDescriptors}};
  const manifestBytes=new TextEncoder().encode(JSON.stringify(manifest));totalPlainBytes+=manifestBytes.length;const manifestChunks=await rc3EncryptAndUploadChunks(client,key,vaultId,'m-',manifestBytes);
  const header={schema:RC3_CLOUD_SCHEMA,kdf:{name:'PBKDF2',hash:'SHA-256',iterations:RC3_KDF_ITERATIONS,salt:bytesToBase64(salt)},manifestChunks};await rc3UploadObject(client,rc3VaultPath(vaultId,'header.bin'),new TextEncoder().encode(JSON.stringify(header)));return {manifest,totalPlainBytes,fileCount:fileDescriptors.length}
}
async function rc3DownloadVault(client,passphrase,vaultId){
  const headerBytes=await rc3DownloadBytes(client,rc3VaultPath(vaultId,'header.bin'));let header;try{header=JSON.parse(new TextDecoder().decode(headerBytes))}catch{throw new Error('Cabeçalho do cofre remoto inválido.')}if(header.schema!==RC3_CLOUD_SCHEMA)throw new Error('Cofre remoto incompatível com esta versão.');const salt=base64ToBytes(header.kdf?.salt||''),key=await rc3DeriveKey(passphrase,salt,Number(header.kdf?.iterations)||RC3_KDF_ITERATIONS),plainManifest=[];for(const ch of header.manifestChunks||[]){const cipher=await rc3DownloadBytes(client,ch.path);try{plainManifest.push(await rc3DecryptBytes(cipher,key,base64ToBytes(ch.iv)))}catch{throw new Error('Senha do cofre incorreta ou conteúdo remoto corrompido.')}}let manifest;try{manifest=JSON.parse(new TextDecoder().decode(rc3ConcatBytes(plainManifest)))}catch{throw new Error('Manifesto descriptografado inválido.')}if(manifest.schema!==RC3_CLOUD_PAYLOAD_SCHEMA)throw new Error('Conteúdo do cofre incompatível.');const prepared={documents:manifest.indexedDB?.documents||[],files:[]};for(const f of manifest.indexedDB?.files||[]){const parts=[];for(const ch of f.chunks||[]){const cipher=await rc3DownloadBytes(client,ch.path);parts.push(await rc3DecryptBytes(cipher,key,base64ToBytes(ch.iv)))}const bytes=rc3ConcatBytes(parts);if(Number.isFinite(Number(f.size))&&bytes.length!==Number(f.size))throw new Error('Arquivo remoto não confere com o tamanho esperado.');prepared.files.push({id:f.id,blob:new Blob([bytes],{type:f.type||'application/octet-stream'})})}return {manifest,prepared}
}
function rc3RebuildCloudUi(){
  const card=$('#cloudAccountCard');if(!card)return;card.innerHTML=`<div class="section-head"><h3>Cofre criptografado da nuvem <span class="badge warn">RC3</span></h3><span class="small">Supabase Auth + RLS + criptografia no navegador</span></div><div class="notice">Ao optar por salvar na nuvem, todo o conteúdo curricular — inclusive XML/XSD, documentos, OCR e arquivos originais — é criptografado no navegador antes do upload. A senha do cofre nunca é enviada ao Supabase e não pode ser recuperada se for perdida.</div><div id="cloudSignedIn"><div class="source"><div><strong>Conta autenticada</strong><span class="small" id="cloudUser"></span></div><span class="badge ok">conectado</span></div><div class="formgrid" style="margin-top:12px"><label>Senha do cofre para salvar<input id="cloudVaultPassword" type="password" autocomplete="new-password" minlength="${RC3_CLOUD_MIN_PASSWORD}" placeholder="mínimo de ${RC3_CLOUD_MIN_PASSWORD} caracteres"></label><label>Confirmar senha do cofre<input id="cloudVaultPasswordConfirm" type="password" autocomplete="new-password" minlength="${RC3_CLOUD_MIN_PASSWORD}" placeholder="redigite a senha"></label><label>Senha do cofre para recuperar<input id="cloudVaultRestorePassword" type="password" autocomplete="off" minlength="${RC3_CLOUD_MIN_PASSWORD}" placeholder="redigite a senha do cofre"></label></div><div class="row" style="margin-top:12px"><button class="btn primary" id="cloudSave">Salvar cofre criptografado</button><button class="btn" id="cloudLoad">Recuperar cofre criptografado</button><button class="btn" id="cloudLogout">Sair</button></div></div><div class="small" id="cloudStatus" style="margin-top:10px"></div>`;
  $('#cloudSave').addEventListener('click',rc3SaveEncryptedCloud);$('#cloudLoad').addEventListener('click',rc3LoadEncryptedCloud);$('#cloudLogout').addEventListener('click',cloudSignOut);renderCloudUi();
}
async function rc3SaveEncryptedCloud(){
  if(!cloudSession?.user)return;const p1=$('#cloudVaultPassword')?.value||'',p2=$('#cloudVaultPasswordConfirm')?.value||'';if(!rc3StrongPass(p1,RC3_CLOUD_MIN_PASSWORD))return cloudStatus(`Use uma senha do cofre com pelo menos ${RC3_CLOUD_MIN_PASSWORD} caracteres.`,'error');if(p1!==p2)return cloudStatus('As duas senhas do cofre não coincidem.','error');const client=await loadSupabaseClient(),vaultId=`v${Date.now()}-${crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}`;cloudStatus('Criptografando documentos e dados antes do upload…');let oldVault='';try{const {data:old,error:oldErr}=await client.from('user_cloud_vaults').select('vault_id').eq('user_id',cloudSession.user.id).maybeSingle();if(oldErr)throw oldErr;oldVault=old?.vault_id||'';const stats=await rc3BuildAndUploadVault(client,p1,vaultId);const {error:pointerError}=await client.from('user_cloud_vaults').upsert({user_id:cloudSession.user.id,vault_id:vaultId,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(pointerError)throw pointerError;await client.from('user_snapshots').delete().eq('user_id',cloudSession.user.id);if(oldVault&&oldVault!==vaultId)rc3DeleteVault(client,oldVault).catch(()=>{});cloudStatus(`Cofre criptografado salvo: ${stats.fileCount} arquivo(s), ${fmtBytes(stats.totalPlainBytes)} protegidos antes do upload.`,'ok')}catch(e){await rc3DeleteVault(client,vaultId).catch(()=>{});cloudStatus('Falha ao salvar o cofre: '+e.message,'error')}finally{if($('#cloudVaultPassword'))$('#cloudVaultPassword').value='';if($('#cloudVaultPasswordConfirm'))$('#cloudVaultPasswordConfirm').value=''}}
async function rc3LoadEncryptedCloud(){
  if(!cloudSession?.user)return;const pass=$('#cloudVaultRestorePassword')?.value||'';if(!pass)return cloudStatus('Redigite a senha do cofre para recuperar os dados.','error');cloudStatus('Baixando e descriptografando o cofre no navegador…');try{const client=await loadSupabaseClient(),{data:pointer,error}=await client.from('user_cloud_vaults').select('vault_id,updated_at').eq('user_id',cloudSession.user.id).maybeSingle();if(error)throw error;if(!pointer?.vault_id)return cloudStatus('Ainda não existe cofre criptografado nesta conta.','warn');const {manifest,prepared}=await rc3DownloadVault(client,pass,pointer.vault_id);if(!confirm(`Recuperar o cofre criptografado salvo em ${new Date(pointer.updated_at).toLocaleString('pt-BR')}?\n\nO estado curricular local e os documentos locais serão substituídos pelo conteúdo descriptografado do cofre.`))return;await rc3ApplyPayload(manifest,prepared);cloudStatus(`Cofre recuperado com segurança: ${prepared.files.length} arquivo(s) original(is) restaurado(s).`,'ok')}catch(e){cloudStatus('Falha ao recuperar o cofre: '+e.message,'error')}finally{if($('#cloudVaultRestorePassword'))$('#cloudVaultRestorePassword').value=''}}
saveCloudSnapshot=rc3SaveEncryptedCloud;loadCloudSnapshot=rc3LoadEncryptedCloud;

function rc3ClearAuthPassword(){const p=document.getElementById('authGatePassword');if(p&&cloudSession?.user)p.value=''}
function rc3Init(){rc3OrganizeNavigation();rc3RebuildBackupUi();rc3RebuildCloudUi();rc3ClearAuthPassword();setTimeout(()=>{rc3ClearAuthPassword();renderCloudUi()},500)}
rc3Init();