function renderIntegralRecords(){
  const cats=[...new Set(state.records.map(r=>r.category))].sort();const filter=$('#recordFilter');const current=state.runtime.recordFilter||'';filter.innerHTML='<option value="">Todas as categorias</option>'+cats.map(c=>`<option value="${esc(c)}" ${c===current?'selected':''}>${esc(RECORD_CATEGORY_LABELS[c]||c)}</option>`).join('');
  const counts=Object.entries(state.records.reduce((m,r)=>(m[r.category]=(m[r.category]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]);$('#categorySummary').innerHTML=counts.length?counts.map(([c,n])=>`<div class="card metric"><div class="n">${n}</div><div class="label">${esc(RECORD_CATEGORY_LABELS[c]||c)}</div></div>`).join(''):'';
  const rows=state.records.filter(r=>!current||r.category===current).sort((a,b)=>(b.year||'').localeCompare(a.year||'')||a.category.localeCompare(b.category));$('#recordCount').textContent=state.records.length?`${rows.length} de ${state.records.length} registro(s)`:'';
  $('#recordBody').innerHTML=rows.length?rows.slice(0,500).map(r=>`<tr><td>${esc(r.year)||'—'}</td><td><span class="badge neutral">${esc(r.categoryLabel)}</span></td><td>${esc(r.subtypeLabel)}</td><td class="titlecell"><strong>${esc(r.title||'—')}</strong>${r.status?`<div class="small">${esc(r.status)}</div>`:''}</td><td>${esc(r.institution||r.person||'—')}${r.person&&r.institution?`<div class="small">${esc(r.person)}</div>`:''}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum registro nesta categoria.</td></tr>';
}
function renderAudit(){
  const missD=state.audit.filter(x=>x.type==='missing-doi').length,missI=state.audit.filter(x=>x.type==='missing-issn').length,dup=state.audit.filter(x=>x.type.includes('duplicate')).length;const dm=state.documents.filter(d=>d.reconciliation?.status==='candidate-missing').length,du=state.documents.filter(d=>d.reconciliation?.status==='uncertain').length;
  $('#aMissingDoi').textContent=missD;$('#aMissingIssn').textContent=missI;$('#aDup').textContent=dup;$('#aDocMissing').textContent=dm;$('#aDocUncertain').textContent=du;
  const denom=Math.max(state.articles.length*3+state.records.length*.25,1),penalty=missD+missI+dup*2+du*.25;const health=(state.articles.length||state.records.length)?Math.max(0,Math.round((1-penalty/denom)*100)):null;$('#health').textContent=health===null?'—':health+'%';
  $('#auditList').innerHTML=state.audit.length?state.audit.map(f=>{const x=f.article||f.record||{};return `<div class="source"><div><strong>${esc(f.message)}</strong><span class="small">${esc(x.year||'')} · ${esc(x.title||x.subtypeLabel||'registro')}</span></div><div class="row"><span class="badge ${f.severity}">${f.severity==='bad'?'revisar':'incompleto'}</span>${f.type==='missing-doi'&&f.article?`<button class="btn" onclick="findDoi('${f.article.id}')">Buscar DOI</button>`:''}</div></div>`}).join(''):'<div class="empty">Nenhuma inconsistência básica detectada.</div>';
  $('#reconciliationList').innerHTML=state.documents.length?state.documents.map(d=>`<div class="source"><div><strong>${esc(d.name)}</strong><span class="small">${esc(d.classification?.label||'')} · ${esc(d.reconciliation?.label||'não reconciliado')}${d.reconciliation?.title?' · '+esc(d.reconciliation.title):''}</span></div>${reconciliationBadge(d.reconciliation)}</div>`).join(''):'<div class="empty">Nenhuma evidência processada.</div>';
}
function reconciliationBadge(r){if(r?.status==='matched')return '<span class="badge ok">localizada</span>';if(r?.status==='candidate-missing')return '<span class="badge bad">revisar ausência</span>';if(r?.status==='uncertain')return '<span class="badge warn">incerta</span>';return '<span class="badge neutral">não comparável</span>'}
function renderUpdates(){
  const missing=state.articles.filter(a=>!a.doi); if(!state.articles.length){$('#updateList').innerHTML='<div class="empty">Importe um currículo para procurar metadados ausentes.</div>';return}
  let html='';
  missing.forEach(a=>{const u=state.updates.find(x=>x.articleId===a.id);html+=`<div class="source"><div><strong>${esc(a.title)}</strong><span class="small">${esc(a.year)} · ${esc(a.journal)||'periódico não informado'}</span>${u?`<div style="margin-top:7px">${u.status==='found'?`<span class="badge ok">DOI sugerido: ${esc(u.doi)}</span> <span class="small">similaridade ${(u.score*100).toFixed(0)}% · Crossref</span>`:`<span class="badge neutral">nenhuma correspondência segura</span>`}</div>`:''}</div><div class="row">${u?.status==='found'?`<button class="btn primary" onclick="approveDoi('${a.id}')">Aprovar sugestão</button><button class="btn" onclick="showUpdate('${a.id}')">Examinar</button>`:`<button class="btn" onclick="findDoi('${a.id}')">Buscar no Crossref</button>`}</div></div>`});
  $('#updateList').innerHTML=html||'<div class="empty">Nenhum artigo sem DOI. A etapa seguinte adicionará comparação mais ampla com fontes externas.</div>';
}
function renderQueue(){
  $('#mQueue').textContent=state.queue.length;$('#exportQueue').disabled=!state.queue.length;$('#clearQueue').disabled=!state.queue.length;
  $('#queueList').innerHTML=state.queue.length?state.queue.map((q,i)=>`<div class="source"><div><strong>${esc(q.operation)}</strong><span class="small">${esc(q.title||'')} · fonte: ${esc(q.evidence?.source||'revisão do usuário')}${q.evidence?.documentName?' · '+esc(q.evidence.documentName):''}</span></div><span class="badge warn">pendente</span></div>`).join(''):'<div class="empty">A fila está vazia.</div>';
}


const DOC_TYPES={
  BANCA:'Banca acadêmica',EVENTO:'Evento / participação',ORIENTACAO:'Orientação',FORMACAO:'Curso / formação complementar',PREMIO:'Prêmio / distinção',GESTAO:'Gestão / comissão / portaria',PROJETO:'Projeto',PRODUCAO_BIBLIOGRAFICA:'Produção bibliográfica',PARECER:'Parecer / avaliação',DOCUMENTO_GENERICO:'Documento acadêmico — revisar'
};
const DB_NAME='lattesAssistEvidenceDB',DB_VERSION=2,STORE='documents',FILE_STORE='files';
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB' in window))return reject(new Error('IndexedDB indisponível'));const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(FILE_STORE))db.createObjectStore(FILE_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbPut(rec){const db=await openDb();return new Promise((resolve,reject)=>{const blob=rec.blob,meta={...rec};delete meta.blob;const tx=db.transaction([STORE,FILE_STORE],'readwrite');tx.objectStore(STORE).put(meta);if(blob)tx.objectStore(FILE_STORE).put({id:rec.id,blob});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function dbGet(id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(id);r.onsuccess=()=>{const v=r.result;db.close();resolve(v)};r.onerror=()=>{db.close();reject(r.error)}})}
async function dbGetBlob(id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(FILE_STORE,'readonly').objectStore(FILE_STORE).get(id);r.onsuccess=()=>{const v=r.result?.blob;db.close();resolve(v)};r.onerror=()=>{db.close();reject(r.error)}})}
async function dbAll(){try{const db=await openDb();return await new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>{const v=r.result||[];db.close();resolve(v)};r.onerror=()=>{db.close();reject(r.error)}})}catch{return []}}
async function dbDelete(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction([STORE,FILE_STORE],'readwrite');tx.objectStore(STORE).delete(id);tx.objectStore(FILE_STORE).delete(id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function loadDocuments(){const rows=await dbAll();state.documents=rows.sort((a,b)=>(b.addedAt||'').localeCompare(a.addedAt||''));state.documents.forEach(d=>d.reconciliation=reconcileDocument(d));renderAll()}
async function sha256(file){if(!crypto?.subtle)return '';const b=await file.arrayBuffer();const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function fmtBytes(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function updateDocProgress(label,pct,detail=''){const el=$('#docProgress');el.classList.add('on');$('#docProgressLabel').textContent=label;$('#docProgressPct').textContent=Math.round(pct)+'%';$('#docProgressBar').style.width=Math.max(0,Math.min(100,pct))+'%';$('#docProgressDetail').textContent=detail}
function hideDocProgress(){setTimeout(()=>$('#docProgress').classList.remove('on'),600)}
