const MANUAL_REFERENCE_SOURCE='ResearchGate (indicação manual)';
const GENERIC_MANUAL_SOURCE='Referência externa manual';
function extractManualDoi(value){const s=String(value||'').trim();const m=s.match(/10\.\d{4,9}\/[-._;()/:A-Z0-9]+/i);return m?m[0].replace(/[.,;:)>\]}]+$/,'').toLowerCase():''}
function validManualUrl(value){try{const u=new URL(String(value||'').trim());return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}}
function isResearchGateUrl(value){try{return /(^|\.)researchgate\.net$/i.test(new URL(value).hostname)}catch{return false}}
function manualSourceName(url){return url&&isResearchGateUrl(url)?MANUAL_REFERENCE_SOURCE:GENERIC_MANUAL_SOURCE}
function manualReferenceStatus(msg,kind=''){const e=$('#manualReferenceStatus');if(e){e.textContent=msg;e.dataset.kind=kind}}
function ensureManualReferenceUi(){const panel=$('#external');if(!panel||$('#manualReferenceCard'))return;const cards=[...panel.querySelectorAll('.section.card')];const config=cards.find(c=>c.querySelector('#externalAuthorName'))||cards[0];if(!config)return;const card=document.createElement('div');card.id='manualReferenceCard';card.className='section card';card.innerHTML=`<div class="section-head"><h3>Referência externa manual</h3><span class="small">ResearchGate ou outra procedência informada pelo usuário</span></div><div class="notice">O Lattes Assist não acessa nem raspa automaticamente o ResearchGate. O link é armazenado apenas como procedência. Informe também um DOI ou título para que os metadados sejam resolvidos por fontes abertas.</div><div class="formgrid"><label>Link da fonte<input id="manualReferenceUrl" type="url" placeholder="https://www.researchgate.net/publication/..."></label><label>DOI ou título<input id="manualReferenceQuery" type="text" placeholder="10.xxxx/xxxxx ou título da produção"></label><label>Ano opcional<input id="manualReferenceYear" type="text" inputmode="numeric" maxlength="4" placeholder="2025"></label></div><div class="row" style="margin-top:12px"><button class="btn primary" id="resolveManualReference">Resolver referência</button><span class="small" id="manualReferenceStatus"></span></div>`;config.insertAdjacentElement('afterend',card);$('#resolveManualReference').onclick=resolveManualReference}
function crossrefItemToManual(x,url){return {source:manualSourceName(url),title:normalizeDisplayText((x.title||[])[0]||''),doi:x.DOI||'',year:x['published-print']?.['date-parts']?.[0]?.[0]||x['published-online']?.['date-parts']?.[0]?.[0]||x.issued?.['date-parts']?.[0]?.[0]||'',venue:normalizeDisplayText((x['container-title']||[])[0]||x.publisher||''),type:x.type||'',authors:(x.author||[]).map(a=>[a.given,a.family].filter(Boolean).join(' ')),raw:{...x,_manualSourceUrl:url,_manualSourceName:manualSourceName(url),_resolvedBy:'Crossref'}}}
function dataCiteItemToManual(x,url){const a=x.attributes||{};return {source:manualSourceName(url),title:normalizeDisplayText((a.titles||[])[0]?.title||''),doi:a.doi||x.id||'',year:a.publicationYear||'',venue:normalizeDisplayText(a.publisher?.name||a.publisher||''),type:a.types?.resourceTypeGeneral||a.types?.resourceType||'',authors:(a.creators||[]).map(c=>c.name||[c.givenName,c.familyName].filter(Boolean).join(' ')).filter(Boolean),raw:{...x,_manualSourceUrl:url,_manualSourceName:manualSourceName(url),_resolvedBy:'DataCite'}}}
async function resolveManualDoi(doi,url){try{const r=await fetch('https://api.crossref.org/works/'+encodeURIComponent(doi));if(r.ok){const j=await r.json();if(j.message)return crossrefItemToManual(j.message,url)}}catch{}try{const r=await fetch('https://api.datacite.org/dois/'+encodeURIComponent(doi));if(r.ok){const j=await r.json();if(j.data)return dataCiteItemToManual(j.data,url)}}catch{}throw new Error('DOI não localizado com segurança no Crossref nem no DataCite.')}
async function resolveManualTitle(title,year,url){const p=new URLSearchParams({'query.bibliographic':crossrefQueryTitle(title),'rows':'8'});if(state.settings.email)p.set('mailto',state.settings.email);const r=await fetch('https://api.crossref.org/works?'+p);if(!r.ok)throw new Error('Crossref respondeu '+r.status);const j=await r.json();const ranked=(j.message?.items||[]).map(x=>{const candidate=crossrefItemToManual(x,url);let score=jaccard(title,candidate.title);if(year&&candidate.year&&String(year)===String(candidate.year))score+=.1;return {candidate,score}}).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best||best.score<.58)throw new Error('Nenhuma correspondência suficientemente segura foi encontrada para o título informado.');best.candidate.raw._manualResolutionScore=best.score;return best.candidate}
async function resolveManualReference(){const rawUrl=clean($('#manualReferenceUrl')?.value),url=validManualUrl(rawUrl),query=clean($('#manualReferenceQuery')?.value),year=clean($('#manualReferenceYear')?.value);if(rawUrl&&!url)return manualReferenceStatus('O link informado não é uma URL HTTP/HTTPS válida.','error');if(!url&&!query)return manualReferenceStatus('Informe um link e/ou DOI/título.','error');const doi=extractManualDoi(query)||extractManualDoi(url);if(url&&isResearchGateUrl(url)&&!doi&&!query)return manualReferenceStatus('Para um link do ResearchGate, informe também o DOI ou título da produção.','warn');const btn=$('#resolveManualReference');btn.disabled=true;manualReferenceStatus('Resolvendo metadados sem acessar a página de procedência…');try{const c=doi?await resolveManualDoi(doi,url):await resolveManualTitle(query,year,url);const rec=addExternalCandidate(c);if(!rec)throw new Error('Não foi possível criar o candidato externo.');rec.manualSourceUrl=url||rec.manualSourceUrl||'';rec.manualSourceKind=url&&isResearchGateUrl(url)?'ResearchGate':'Referência externa manual';rec.classification=inferExternalProductionType(rec);rec.reconciliation=candidateSimilarity(rec);rec.identity=scoreIdentity(rec);state.externalSources.push(manualSourceName(url));renderExternal();save();manualReferenceStatus(`Referência resolvida por ${c.raw?._resolvedBy||'fonte aberta'} e adicionada aos candidatos externos.`,'ok')}catch(e){manualReferenceStatus(e.message,'error')}finally{btn.disabled=false}}
function manualCandidateUrl(x){if(x?.manualSourceUrl)return x.manualSourceUrl;const raws=[x?.raw,...Object.values(x?.rawBySource||{})].filter(Boolean);for(const r of raws){if(r?._manualSourceUrl)return r._manualSourceUrl}return ''}
const __renderExternalManualReference=renderExternal;
renderExternal=function(){__renderExternalManualReference();const cards=[...document.querySelectorAll('#externalList>.source')];cards.forEach(card=>{const title=card.querySelector('strong')?.textContent||'',x=state.externalCandidates.find(c=>normalizeTitle(c.title||'')===normalizeTitle(title));if(!x)return;const url=manualCandidateUrl(x);if(!url||card.querySelector('.manual-source-link'))return;const main=card.querySelector('div');const line=document.createElement('div');line.className='small manual-source-link';line.style.marginTop='5px';const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=isResearchGateUrl(url)?'Procedência informada: ResearchGate':'Abrir link de procedência informado';line.appendChild(a);main?.appendChild(line)})};
const __queueExternalManualReference=queueExternal;
queueExternal=function(id){const x=state.externalCandidates.find(c=>c.id===id),url=manualCandidateUrl(x),before=state.queue.length;__queueExternalManualReference(id);if(!url)return;const q=state.queue.slice(before).find(q=>q.evidence?.externalCandidateId===id)||state.queue.find(q=>q.evidence?.externalCandidateId===id);if(q){q.evidence=q.evidence||{};q.evidence.manualSourceUrl=url;q.evidence.manualSourceKind=isResearchGateUrl(url)?'ResearchGate':'Referência externa manual';save();renderQueue()}};
ensureManualReferenceUi();