async function queueDocument(id){const d=state.documents.find(x=>x.id===id);if(!d||d.queued)return;if(d.classification?.type==='DOCUMENTO_GENERICO'&&!confirm('A classificação ainda é genérica. Deseja enviar a evidência à fila para revisão mesmo assim?'))return;const matched=d.reconciliation?.status==='matched';state.assistedPackage=null;state.rebuiltXml=null;state.rebuildReport=null;state.diffReport=null;state.semanticDiff=[];state.stableIdentityReport=null;state.queue.push({id:crypto.randomUUID?crypto.randomUUID():'q'+Date.now(),operation:matched?'VINCULAR_EVIDENCIA_A_REGISTRO':operationForDoc(d.classification.type),targetId:matched?(d.reconciliation.recordId||d.reconciliation.articleId||null):null,title:d.fields?.title||d.classification.label||d.name,patch:{classification:d.classification.type,fields:d.fields,textExcerpt:(d.text||'').slice(0,900)},evidence:{source:'Documento local',documentId:d.id,documentName:d.name,sha256:d.sha256,extractionMethod:d.extraction?.method,confidence:d.extraction?.confidence,retrievedAt:d.addedAt},approvedAt:new Date().toISOString(),status:'pending'});d.queued=true;await dbPut(d);save();renderAll()}
async function removeDocument(id){const d=state.documents.find(x=>x.id===id);if(!d)return;if(!confirm(`Excluir “${d.name}” do arquivo local de evidências? O arquivo original armazenado neste aplicativo também será removido.`))return;await dbDelete(id);state.documents=state.documents.filter(x=>x.id!==id);state.queue=state.queue.filter(q=>q.evidence?.documentId!==id);save();renderAll()}
function exportEvidence(){download('lattes-assist-evidencias.json',JSON.stringify({schema:'lattes-assist.evidence.v1.6',generatedAt:new Date().toISOString(),cv:state.cv,documents:state.documents.map(d=>({...d,text:d.text}))},null,2))}
async function addDemoDocument(){const samples=[
 [`UNIVERSIDADE DE DEMONSTRAÇÃO
Programa de Pós-Graduação em Letras
CERTIFICADO
Certificamos que Pesquisador de Demonstração participou como membro da banca examinadora da defesa de dissertação intitulada “Forma, memória e narrativa contemporânea”, realizada em 12/08/2024.`, '2024_certificado_banca_demonstracao.txt'],
 [`ASSOCIAÇÃO DE DEMONSTRAÇÃO
CERTIFICADO
Certificamos que Pesquisador de Demonstração apresentou a comunicação intitulada “Literatura, arquivo e sobrevivência” no Seminário Nacional de Arquivos Literários, realizado em 18/09/2026.`, '2026_certificado_evento_nao_cadastrado.txt'],
 [`DECLARAÇÃO
Declaramos que Pesquisador de Demonstração participou de atividade acadêmica na Universidade de Demonstração em 2025.`, '2025_declaracao_generica.txt']];
 const files=samples.map(([text,name])=>new File([text],name,{type:'text/plain'}));await processFiles(files)}

async function findDoi(id){
  const a=state.articles.find(x=>x.id===id);if(!a)return;
  try{
    const params=new URLSearchParams({'query.bibliographic':a.title,'rows':'5','select':'DOI,title,author,published-print,published-online,container-title,ISSN,volume,issue,page'});if(state.settings.email)params.set('mailto',state.settings.email);
    const r=await fetch('https://api.crossref.org/works?'+params.toString());if(!r.ok)throw new Error('Crossref respondeu '+r.status);const j=await r.json();
    const candidates=(j.message?.items||[]).map(x=>({raw:x,title:(x.title||[])[0]||'',doi:x.DOI||'',year:(x['published-print']?.['date-parts']?.[0]?.[0]||x['published-online']?.['date-parts']?.[0]?.[0]||'').toString()})).map(x=>({...x,score:jaccard(a.title,x.title)+(a.year&&x.year&&a.year===x.year?.toString()?.trim()?0.08:0)})).sort((x,y)=>y.score-x.score);
    const best=candidates[0]; const safe=best&&best.doi&&best.score>=.68;
    const upd={articleId:id,status:safe?'found':'none',doi:safe?best.doi:'',score:best?.score||0,candidates:candidates.slice(0,3),checkedAt:new Date().toISOString(),source:'Crossref'};
    state.updates=state.updates.filter(x=>x.articleId!==id);state.updates.push(upd);renderUpdates();
  }catch(e){alert('Não foi possível consultar o Crossref: '+e.message)}
}
async function findAll(){for(const a of state.articles.filter(x=>!x.doi)){await findDoiSilent(a.id);renderUpdates()}}
async function findDoiSilent(id){const a=state.articles.find(x=>x.id===id);try{const params=new URLSearchParams({'query.bibliographic':a.title,'rows':'5','select':'DOI,title,author,published-print,published-online,container-title,ISSN,volume,issue,page'});if(state.settings.email)params.set('mailto',state.settings.email);const r=await fetch('https://api.crossref.org/works?'+params);const j=await r.json();const cs=(j.message?.items||[]).map(x=>({raw:x,title:(x.title||[])[0]||'',doi:x.DOI||'',year:(x['published-print']?.['date-parts']?.[0]?.[0]||x['published-online']?.['date-parts']?.[0]?.[0]||'').toString()})).map(x=>({...x,score:jaccard(a.title,x.title)+(a.year&&x.year&&a.year===x.year?0.08:0)})).sort((x,y)=>y.score-x.score);const b=cs[0],safe=b&&b.doi&&b.score>=.68;state.updates=state.updates.filter(x=>x.articleId!==id);state.updates.push({articleId:id,status:safe?'found':'none',doi:safe?b.doi:'',score:b?.score||0,candidates:cs.slice(0,3),checkedAt:new Date().toISOString(),source:'Crossref'});}catch{state.updates=state.updates.filter(x=>x.articleId!==id);state.updates.push({articleId:id,status:'error',doi:'',score:0,candidates:[],source:'Crossref'});}}
function approveDoi(id){const a=state.articles.find(x=>x.id===id),u=state.updates.find(x=>x.articleId===id);if(!a||!u?.doi)return; if(state.queue.some(q=>q.operation==='ATUALIZAR_ARTIGO'&&q.targetId===id&&q.patch?.doi===u.doi))return alert('Essa operação já está na fila.');state.assistedPackage=null;state.rebuiltXml=null;state.rebuildReport=null;state.diffReport=null;state.semanticDiff=[];state.stableIdentityReport=null;state.queue.push({id:crypto.randomUUID?crypto.randomUUID():'q'+Date.now(),operation:'ATUALIZAR_ARTIGO',targetId:id,title:a.title,patch:{doi:u.doi},evidence:{source:'Crossref',retrievedAt:u.checkedAt,score:u.score},approvedAt:new Date().toISOString(),status:'pending'});save();renderQueue();renderAll();}
function showUpdate(id){const a=state.articles.find(x=>x.id===id),u=state.updates.find(x=>x.articleId===id);$('#dialogTitle').textContent='Correspondências do Crossref';$('#dialogBody').innerHTML=`<p><strong>Registro Lattes:</strong> ${esc(a.title)}</p>`+(u?.candidates||[]).map((c,i)=>`<div class="source"><div><strong>${i+1}. ${esc(c.title)}</strong><span class="small">DOI ${esc(c.doi)} · ano ${esc(c.year)} · similaridade ${(c.score*100).toFixed(0)}%</span></div></div>`).join('');$('#detailDialog').showModal()}
function download(name,data,type='application/json'){const blob=new Blob([data],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportAudit(){download('lattes-assist-auditoria.json',JSON.stringify({schema:'lattes-assist.audit.v1.6',cv:state.cv,generatedAt:new Date().toISOString(),findings:state.audit,reconciliation:state.documents.map(d=>({documentId:d.id,name:d.name,classification:d.classification,reconciliation:d.reconciliation}))},null,2))}
function exportQueue(){download('lattes-assist-fila.json',JSON.stringify({schema:'lattes-assist.queue.v1.6',cv:state.cv,generatedAt:new Date().toISOString(),operations:state.queue},null,2))}

async function clearQueueAll(){if(!confirm('Limpar todas as operações pendentes?'))return;state.queue=[];state.assistedPackage=null;state.rebuiltXml=null;state.rebuildReport=null;state.diffReport=null;state.semanticDiff=[];state.stableIdentityReport=null;for(const d of state.documents){if(d.queued){d.queued=false;try{await dbPut(d)}catch{}}}save();renderAll()}

