const EXTERNAL_CLASSIFICATIONS={
  ARTIGO:{label:'Artigo em periódico',category:'PRODUCAO_BIBLIOGRAFICA',subtype:'ARTIGO-PUBLICADO',operation:'CRIAR_ARTIGO'},
  LIVRO:{label:'Livro publicado/organizado',category:'PRODUCAO_BIBLIOGRAFICA',subtype:'LIVRO-PUBLICADO-OU-ORGANIZADO',operation:'CRIAR_LIVRO'},
  CAPITULO:{label:'Capítulo de livro',category:'PRODUCAO_BIBLIOGRAFICA',subtype:'CAPITULO-DE-LIVRO-PUBLICADO',operation:'CRIAR_CAPITULO_LIVRO'},
  EVENTO:{label:'Trabalho em evento',category:'PRODUCAO_BIBLIOGRAFICA',subtype:'TRABALHO-EM-EVENTOS',operation:'CRIAR_TRABALHO_EVENTO'},
  PREPRINT:{label:'Preprint / working paper',category:'PRODUCAO_BIBLIOGRAFICA',subtype:'OUTRA-PRODUCAO-BIBLIOGRAFICA',operation:'CRIAR_OUTRA_PRODUCAO_BIBLIOGRAFICA'},
  TEXTO:{label:'Texto em jornal/revista',category:'PRODUCAO_BIBLIOGRAFICA',subtype:'TEXTO-EM-JORNAL-OU-REVISTA',operation:'CRIAR_TEXTO_JORNAL_REVISTA'},
  SOFTWARE:{label:'Software',category:'PRODUCAO_TECNICA',subtype:'SOFTWARE',operation:'CRIAR_SOFTWARE'},
  DATASET:{label:'Dataset / conjunto de dados',category:'PRODUCAO_TECNICA',subtype:'OUTRA-PRODUCAO-TECNICA',operation:'CRIAR_PRODUCAO_TECNICA'},
  RELATORIO:{label:'Relatório / nota técnica',category:'PRODUCAO_TECNICA',subtype:'RELATORIO-DE-PESQUISA',operation:'CRIAR_RELATORIO_PESQUISA'},
  PARECER:{label:'Parecer / revisão por pares',category:'PRODUCAO_TECNICA',subtype:'OUTRA-PRODUCAO-TECNICA',operation:'CRIAR_ATIVIDADE_TECNICA'},
  PATENTE:{label:'Patente',category:'PRODUCAO_TECNICA',subtype:'PATENTE',operation:'CRIAR_PATENTE'},
  FORMACAO:{label:'Tese / dissertação — revisar formação',category:'FORMACAO',subtype:'FORMACAO-ACADEMICA-TITULACAO',operation:'REVISAR_FORMACAO_TITULACAO'},
  OUTRO:{label:'Outra produção — revisar',category:'OUTRO',subtype:'',operation:'REVISAR_PRODUCAO_EXTERNA'}
};
function normalizedExternalType(x){return normalizeTitle([x.type,x.raw?.type,x.raw?.attributes?.types?.resourceTypeGeneral,x.raw?.attributes?.types?.resourceType,x.raw?.metadata?.upload_type,x.raw?.metadata?.publication_type].filter(Boolean).join(' '))}
function inferExternalProductionType(x){
  const t=normalizedExternalType(x),title=normalizeTitle(x.title||''),venue=normalizeTitle(x.venue||'');const has=(...xs)=>xs.some(v=>t===v||t.includes(v));let key='OUTRO',confidence=.52,reasons=[];
  if(has('journal article','journal-article','article-journal','article')){key='ARTIGO';confidence=.96;reasons.push('tipo declarado como artigo')}
  else if(has('book chapter','book-chapter','book section','book-section','section','chapter')){key='CAPITULO';confidence=.95;reasons.push('tipo declarado como capítulo/seção')}
  else if(has('proceedings article','proceedings-article','conference paper','conference-paper','conferencepaper')){key='EVENTO';confidence=.95;reasons.push('tipo declarado como trabalho em evento')}
  else if(has('edited book','edited-book','monograph','book')){key='LIVRO';confidence=.93;reasons.push('tipo declarado como livro')}
  else if(has('preprint','posted content','posted-content','working paper','working-paper')){key='PREPRINT';confidence=.91;reasons.push('tipo declarado como preprint/working paper')}
  else if(has('software','computer program','computer-program')){key='SOFTWARE';confidence=.97;reasons.push('tipo declarado como software')}
  else if(has('dataset','data set','data-paper','data paper')){key='DATASET';confidence=.95;reasons.push('tipo declarado como dataset')}
  else if(has('report','report component','report-component','technical note','technical-note','deliverable')){key='RELATORIO';confidence=.9;reasons.push('tipo declarado como relatório/nota técnica')}
  else if(has('patent')){key='PATENTE';confidence=.98;reasons.push('tipo declarado como patente')}
  else if(has('dissertation','thesis')){key='FORMACAO';confidence=.9;reasons.push('tipo declarado como tese/dissertação')}
  else if(has('peer review','peer-review','review')){key='PARECER';confidence=.93;reasons.push('registro ORCID de peer review')}
  else if(has('newspaper article','newspaper-article','magazine article','magazine-article')){key='TEXTO';confidence=.91;reasons.push('tipo declarado como texto jornalístico/revista')}
  else if(/\banais\b|proceedings|congress|conference|congresso|seminario|seminário|simposio|simpósio/.test(venue+' '+title)){key='EVENTO';confidence=.7;reasons.push('veículo/título indica evento')}
  else if(/\bcapitulo\b|\bcapítulo\b/.test(title)){key='CAPITULO';confidence=.68;reasons.push('título indica capítulo')}
  else if(x.doi&&venue){key='ARTIGO';confidence=.62;reasons.push('DOI + veículo sugerem artigo, requer conferência')}
  const spec=EXTERNAL_CLASSIFICATIONS[key];return {key,...spec,confidence,reasons,rawType:x.type||''};
}
function mergeExternalCandidate(existing,c){existing.sources=[...new Set([...(existing.sources||[]),c.source].filter(Boolean))];if(!existing.doi&&c.doi)existing.doi=normalizeDoi(c.doi);if(!existing.venue&&c.venue)existing.venue=clean(c.venue);if(!existing.type&&c.type)existing.type=clean(c.type);if((c.authors||[]).length>(existing.authors||[]).length)existing.authors=c.authors;existing.rawBySource=existing.rawBySource||{};if(c.source)existing.rawBySource[c.source]=c.raw||null;if(c.orcidVerified)existing.orcidVerified=true;existing.classification=inferExternalProductionType(existing);existing.reconciliation=candidateSimilarity(existing);existing.identity=scoreIdentity(existing);if(existing.orcidVerified){existing.identity.score=Math.max(existing.identity.score,.86);existing.identity.label='alta confiança';existing.identity.signals=[...new Set([...(existing.identity.signals||[]),'produção recuperada do ORCID informado'])]}}
function addExternalCandidate(c){const doi=normalizeDoi(c.doi),title=clean(c.title),year=String(c.year||'');let existing=null;if(doi)existing=state.externalCandidates.find(x=>normalizeDoi(x.doi)===doi);if(!existing&&title)existing=state.externalCandidates.find(x=>String(x.year||'')===year&&jaccard(x.title||'',title)>=.91);if(existing){mergeExternalCandidate(existing,{...c,doi,title,year});return existing}const rec={id:crypto.randomUUID?crypto.randomUUID():'ext-'+Date.now()+Math.random(),key:[doi,normalizeTitle(title),year].join('|'),title,year,doi,venue:clean(c.venue),type:clean(c.type),authors:c.authors||[],sources:[c.source].filter(Boolean),raw:c.raw||null,rawBySource:{},orcidVerified:Boolean(c.orcidVerified)};if(c.source)rec.rawBySource[c.source]=c.raw||null;rec.classification=inferExternalProductionType(rec);rec.reconciliation=candidateSimilarity(rec);rec.identity=scoreIdentity(rec);if(rec.orcidVerified){rec.identity.score=Math.max(rec.identity.score,.86);rec.identity.label='alta confiança';rec.identity.signals=[...new Set([...(rec.identity.signals||[]),'produção recuperada do ORCID informado'])]}state.externalCandidates.push(rec);return rec}
async function queryCrossrefExternal(name){const p=new URLSearchParams({'query.author':name,'rows':'100','select':'DOI,title,author,published-print,published-online,container-title,type,ISBN,ISSN,publisher'});if(state.settings.email)p.set('mailto',state.settings.email);const r=await fetch('https://api.crossref.org/works?'+p);if(!r.ok)throw new Error('Crossref '+r.status);const j=await r.json();(j.message?.items||[]).forEach(x=>addExternalCandidate({source:'Crossref',title:normalizeDisplayText((x.title||[])[0]||''),doi:x.DOI||'',year:x['published-print']?.['date-parts']?.[0]?.[0]||x['published-online']?.['date-parts']?.[0]?.[0]||'',venue:normalizeDisplayText((x['container-title']||[])[0]||x.publisher||''),type:x.type||'',authors:(x.author||[]).map(a=>[a.given,a.family].filter(Boolean).join(' ')),raw:x}));state.externalSources.push('Crossref')}
async function openAlexAuthor(name,orcid){if(orcid){const r=await fetch('https://api.openalex.org/authors/'+encodeURIComponent('https://orcid.org/'+orcid));if(r.ok)return r.json();if(r.status!==404)throw new Error('OpenAlex autor '+r.status)}if(!name)return null;const r=await fetch('https://api.openalex.org/authors?search='+encodeURIComponent(name)+'&per_page=5');if(!r.ok)throw new Error('OpenAlex autores '+r.status);const j=await r.json();const ranked=(j.results||[]).map(a=>({a,score:jaccard(name,a.display_name||'')})).sort((x,y)=>y.score-x.score);return ranked[0]?.score>=.55?ranked[0].a:null}
async function queryOpenAlexExternal(name,orcid){const author=await openAlexAuthor(name,orcid);if(!author?.id)throw new Error('OpenAlex: autor não identificado com segurança');const authorId=author.id.split('/').pop();const r=await fetch('https://api.openalex.org/works?filter=author.id:'+encodeURIComponent(authorId)+'&per_page=100&corpus=all');if(!r.ok)throw new Error('OpenAlex trabalhos '+r.status);const j=await r.json();(j.results||[]).forEach(x=>addExternalCandidate({source:'OpenAlex',title:normalizeDisplayText(x.display_name||x.title||''),doi:x.doi||'',year:x.publication_year||'',venue:normalizeDisplayText(x.primary_location?.source?.display_name||''),type:x.type||'',authors:(x.authorships||[]).map(a=>a.author?.display_name).filter(Boolean),raw:{...x,_matchedAuthor:{id:author.id,display_name:author.display_name,orcid:author.orcid}},orcidVerified:Boolean(orcid&&author.orcid)}));state.externalSources.push('OpenAlex')}
async function queryDataCiteExternal(name,orcid){const p=new URLSearchParams({'page[size]':'100','affiliation':'true','publisher':'true'});if(orcid)p.set('user-id',orcid);else if(name)p.set('query','creators.name:"'+name.replace(/"/g,'')+'"');const r=await fetch('https://api.datacite.org/dois?'+p);if(!r.ok)throw new Error('DataCite '+r.status);const j=await r.json();(j.data||[]).forEach(x=>{const a=x.attributes||{},creators=a.creators||[],orcidHit=Boolean(orcid&&creators.some(c=>(c.nameIdentifiers||[]).some(n=>String(n.nameIdentifier||'').includes(orcid))));addExternalCandidate({source:'DataCite',title:normalizeDisplayText((a.titles||[])[0]?.title||''),doi:a.doi||x.id||'',year:a.publicationYear||'',venue:normalizeDisplayText(a.publisher?.name||a.publisher||''),type:a.types?.resourceTypeGeneral||a.types?.resourceType||'',authors:creators.map(c=>c.name||[c.givenName,c.familyName].filter(Boolean).join(' ')).filter(Boolean),raw:x,orcidVerified:orcidHit})});state.externalSources.push('DataCite')}
function orcidWorkDoi(s){return (s?.['external-ids']?.['external-id']||[]).find(e=>String(e['external-id-type']||'').toLowerCase()==='doi')?.['external-id-value']||''}
async function queryOrcidExternal(orcid){const c=await loadSupabaseClient();const {data,error}=await c.functions.invoke('orcid-public',{body:{orcid}});if(error)throw new Error('ORCID backend: '+error.message);if(!data?.configured)throw new Error('ORCID Public API ainda sem credenciais de cliente no backend');(data.works?.group||[]).forEach(g=>{const s=(g['work-summary']||[])[0]||{};addExternalCandidate({source:'ORCID',title:normalizeDisplayText(s.title?.title?.value||''),doi:orcidWorkDoi(s),year:s['publication-date']?.year?.value||'',venue:normalizeDisplayText(s['journal-title']?.value||''),type:s.type||'',authors:[state.cv?.name||''].filter(Boolean),raw:s,orcidVerified:true})});const groups=data.peerReviews?.group||data.peerReviews?.['peer-review-group']||[];groups.forEach(g=>{const items=g['peer-review-summary']||g['peer-review']||[];items.forEach(s=>addExternalCandidate({source:'ORCID',title:normalizeDisplayText(s['subject-name']?.title?.value||s['subject-name']?.value||s['review-group-id']||'Revisão por pares'),doi:'',year:s['completion-date']?.year?.value||'',venue:normalizeDisplayText(s['convening-organization']?.name||s['review-group-id']||''),type:'peer-review',authors:[state.cv?.name||''].filter(Boolean),raw:s,orcidVerified:true}))});state.externalSources.push('ORCID')}
function ensureExternalProspectingUi(){const row=document.querySelector('#external .section.card .row');if(row&&!document.getElementById('externalProspectingInfo')){const info=document.createElement('span');info.id='externalProspectingInfo';info.className='small';info.style.marginLeft='8px';info.textContent='Crossref · OpenAlex · DataCite · ORCID';row.appendChild(info)}const hint=document.querySelector('#external .section.card .hint');if(hint)hint.textContent='ORCID usa a Public API 3.0 por um conector seguro no backend. Crossref, OpenAlex e DataCite são consultados como fontes abertas. Resultados são deduplicados por DOI e por título/ano antes da classificação.'}
function productionBadge(c){const x=c.classification||inferExternalProductionType(c),cls=x.confidence>=.85?'ok':x.confidence>=.65?'warn':'neutral';return `<span class="badge ${cls}">${esc(x.label)} · ${Math.round(x.confidence*100)}%</span>`}
function renderExternal(){ensureExternalProspectingUi();const xs=state.externalCandidates;xs.forEach(x=>{x.classification=inferExternalProductionType(x);x.reconciliation=candidateSimilarity(x);x.identity=scoreIdentity(x);if(x.orcidVerified){x.identity.score=Math.max(x.identity.score,.86);x.identity.label='alta confiança';x.identity.signals=[...new Set([...(x.identity.signals||[]),'ORCID coincidente'])]}});$('#xCandidates').textContent=xs.length;$('#xLikelyNew').textContent=xs.filter(x=>x.reconciliation?.status==='likely-new').length;$('#xMatched').textContent=xs.filter(x=>x.reconciliation?.status==='matched').length;$('#xSources').textContent=new Set(state.externalSources).size;$('#xHighIdentity').textContent=xs.filter(x=>(x.identity?.score||0)>=.72).length;$('#exportExternal').disabled=!xs.length;$('#externalMeta').textContent=xs.length?`${xs.length} candidato(s) · ${new Set(state.externalSources).size} fonte(s) · ${xs.filter(x=>x.classification?.key!=='OUTRO').length} com tipo reconhecido`:'';$('#scanExternal').disabled=!state.cv;if(!xs.length){$('#externalList').innerHTML='<div class="empty">Nenhum candidato externo carregado.</div>';return}$('#externalList').innerHTML=xs.sort((a,b)=>(b.year||'').localeCompare(a.year||'')).map(x=>{const queued=state.queue.some(q=>q.evidence?.externalKey===x.key||q.evidence?.externalCandidateId===x.id),canQueue=x.reconciliation?.status==='likely-new'&&(x.identity?.score||0)>=.5;return `<div class="source"><div><strong>${esc(x.title||'Sem título')}</strong><span class="small">${esc(x.year||'')} · ${esc(x.venue||'')} · ${esc((x.sources||[]).join(', '))}${x.doi?' · DOI '+esc(x.doi):''}</span><div style="margin-top:6px">${productionBadge(x)} ${x.reconciliation?.status==='matched'?'<span class="badge ok">já correspondente</span>':x.reconciliation?.status==='uncertain'?'<span class="badge warn">correspondência incerta</span>':'<span class="badge bad">provável ausência</span>'} <span class="badge ${x.identity?.score>=.72?'ok':x.identity?.score>=.5?'warn':'neutral'}">${esc(x.identity?.label||'identidade não avaliada')} ${x.identity?.score?Math.round(x.identity.score*100)+'%':''}</span>${x.classification?.reasons?.length?`<div class="small" style="margin-top:5px">tipo: ${esc(x.classification.reasons.join('; '))}</div>`:''}${x.identity?.signals?.length?`<div class="small" style="margin-top:4px">identidade: ${esc(x.identity.signals.join('; '))}</div>`:''}</div></div><div class="row">${queued?'<span class="badge ok">na fila</span>':canQueue?`<button class="btn primary" onclick="queueExternal('${x.id}')">Adicionar como ${esc(x.classification.label.toLowerCase())}</button>`:x.reconciliation?.status==='likely-new'?'<span class="badge neutral">identidade insuficiente</span>':''}</div></div>`}).join('');if(typeof renderDecisions==='function')renderDecisions()}
function queueExternal(id){const x=state.externalCandidates.find(c=>c.id===id);if(!x)return;const cls=x.classification||inferExternalProductionType(x);if((x.identity?.score||0)<.5)return alert('A confiança de identidade é insuficiente para colocar este candidato na fila.');if(state.queue.some(q=>q.evidence?.externalKey===x.key||q.evidence?.externalCandidateId===id))return alert('Este candidato já está na fila.');if(cls.key==='OUTRO'&&!confirm('O tipo da produção não pôde ser reconhecido com segurança. Adicionar à fila para revisão manual?'))return;state.assistedPackage=null;state.rebuiltXml=null;state.rebuildReport=null;state.diffReport=null;state.semanticDiff=[];state.stableIdentityReport=null;state.queue.push({id:crypto.randomUUID?crypto.randomUUID():'q'+Date.now(),operation:cls.operation,targetId:null,title:x.title,patch:{year:x.year,doi:x.doi,venue:x.venue,type:x.type,authors:x.authors,classification:{key:cls.key,label:cls.label,category:cls.category,subtype:cls.subtype,confidence:cls.confidence,reasons:cls.reasons}},evidence:{source:(x.sources||[]).join(', '),externalCandidateId:id,externalKey:x.key,identityScore:x.identity?.score||0,reconciliationScore:x.reconciliation?.score||0,retrievedAt:new Date().toISOString()},approvedAt:new Date().toISOString(),status:'pending'});save();renderAll();renderExternal()}
async function scanExternal(){const name=clean($('#externalAuthorName').value)||state.cv?.name||'',orcid=clean($('#externalOrcid').value)||state.settings.orcid||'';if(!name&&!orcid)return alert('Informe o nome ou ORCID para a prospecção.');if(orcid){state.settings.orcid=orcid;save();buildIdentityProfile()}state.externalCandidates=[];state.externalSources=[];const btn=$('#scanExternal');btn.disabled=true;btn.textContent='Prospectando…';const errors=[];if($('#useOrcid').checked&&orcid)try{await queryOrcidExternal(orcid)}catch(e){errors.push(e.message)}if($('#useOpenAlex').checked)try{await queryOpenAlexExternal(name,orcid)}catch(e){errors.push(e.message)}if($('#useDataCite').checked)try{await queryDataCiteExternal(name,orcid)}catch(e){errors.push(e.message)}if($('#useCrossref').checked&&name)try{await queryCrossrefExternal(name)}catch(e){errors.push(e.message)}buildIdentityProfile();state.externalCandidates.forEach(c=>{c.reconciliation=candidateSimilarity(c);c.identity=scoreIdentity(c);c.classification=inferExternalProductionType(c);if(c.orcidVerified){c.identity.score=Math.max(c.identity.score,.86);c.identity.label='alta confiança';c.identity.signals=[...new Set([...(c.identity.signals||[]),'ORCID coincidente'])]}});renderExternal();btn.textContent='Prospectar produção';btn.disabled=!state.cv;if(errors.length)alert('Prospecção concluída, mas algumas fontes exigem atenção:\n\n'+[...new Set(errors)].join('\n'))}
function exportExternal(){download('lattes-assist-candidatos-externos.json',JSON.stringify({schema:'lattes-assist.external.v1.7',generatedAt:new Date().toISOString(),cv:state.cv,sources:[...new Set(state.externalSources)],candidates:state.externalCandidates.map(x=>({...x,classification:x.classification||inferExternalProductionType(x)}))},null,2))}
ensureExternalProspectingUi();