const XML_ENCODING_MARKERS=['�','Ã','Â','â€','â€“','â€”','â€œ','â€','â€™'];
function mojibakeScore(s){const t=String(s||'');let n=0;for(const m of XML_ENCODING_MARKERS)n+=(t.split(m).length-1)*(m==='�'?5:1);return n}
function latin1BytesFromString(s){const out=new Uint8Array(s.length);for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);if(c>255)return null;out[i]=c}return out}
function repairMojibake(s){const original=String(s||'');if(!original||mojibakeScore(original)===0)return original;const bytes=latin1BytesFromString(original);if(!bytes)return original;try{const candidate=new TextDecoder('utf-8',{fatal:true}).decode(bytes);return mojibakeScore(candidate)<mojibakeScore(original)?candidate:original}catch{return original}}
function normalizeDisplayText(s){return repairMojibake(String(s||'')).normalize('NFC').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim()}
function normalizeForSearch(s){return normalizeDisplayText(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[“”„‟«»'’‘`´]/g,' ').replace(/[–—−]/g,'-').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim()}
function normalizeTitle(s){return normalizeForSearch(s)}
function crossrefQueryTitle(s){return normalizeDisplayText(s).replace(/[“”„‟«»]/g,'"').replace(/[’‘]/g,"'").replace(/[–—−]/g,'-').replace(/\s+/g,' ').trim()}
function detectXmlEncoding(bytes){if(bytes.length>=3&&bytes[0]===0xEF&&bytes[1]===0xBB&&bytes[2]===0xBF)return 'utf-8';if(bytes.length>=2&&bytes[0]===0xFF&&bytes[1]===0xFE)return 'utf-16le';if(bytes.length>=2&&bytes[0]===0xFE&&bytes[1]===0xFF)return 'utf-16be';const head=[...bytes.slice(0,512)].map(b=>String.fromCharCode(b)).join('');const m=head.match(/<\?xml[^>]*encoding\s*=\s*["']([^"']+)["']/i);if(!m)return 'utf-8';const enc=m[1].toLowerCase().replace(/_/g,'-');if(enc==='iso-8859-1'||enc==='latin1'||enc==='latin-1')return 'windows-1252';if(enc==='utf8')return 'utf-8';return enc}
async function decodeXmlFile(file){const bytes=new Uint8Array(await file.arrayBuffer());const declared=detectXmlEncoding(bytes);let text='';let used=declared;try{text=new TextDecoder(declared,{fatal:false}).decode(bytes)}catch{used='utf-8';text=new TextDecoder('utf-8',{fatal:false}).decode(bytes)}const repaired=repairMojibake(text);const corrected=repaired!==text;return {text:repaired,encoding:used,declaredEncoding:declared,corrected,mojibakeBefore:mojibakeScore(text),mojibakeAfter:mojibakeScore(repaired)}}
function encodingDiagnosticLabel(info){if(!info)return '';const parts=[`codificação ${info.encoding||'utf-8'}`];if(info.corrected)parts.push('mojibake corrigido');return parts.join(' · ')}
