const CLASSIFICATION_CHOICES=()=>Object.entries(EXTERNAL_CLASSIFICATIONS).filter(([k])=>k!=='OUTRO').sort((a,b)=>a[1].label.localeCompare(b[1].label,'pt-BR'));
const __inferProductionAutomatic=inferExternalProductionType;
inferExternalProductionType=function(x){return x?.manualClassification?.key?x.manualClassification:__inferProductionAutomatic(x)};
function manualClassificationFor(key){const spec=EXTERNAL_CLASSIFICATIONS[key]||EXTERNAL_CLASSIFICATIONS.OUTRO;return {key,...spec,confidence:1,reasons:['reclassificado manualmente pelo usuário'],manual:true,rawType:''}}
function ensureReclassifyDialog(){if($('#reclassifyDialog'))return;const d=document.createElement('dialog');d.id='reclassifyDialog';d.className='dialog';d.innerHTML=`<div class="inner"><h3>Reclassificar categoria / tipo</h3><p class="hint" id="reclassifyContext"></p><label class="hint">Tipo curricular</label><select id="reclassifySelect" class="btn" style="width:100%;margin-top:6px"></select><div id="reclassifyCurrent" class="small" style="margin-top:10px"></div><div class="row" style="justify-content:flex-end;margin-top:18px"><button class="btn" id="reclassifyCancel">Cancelar</button><button class="btn primary" id="reclassifySave">Aplicar reclassificação</button></div></div>`;document.body.appendChild(d);$('#reclassifyCancel').onclick=()=>d.close()}
let RECLASSIFY_TARGET=null;
function openReclassify(kind,id){ensureReclassifyDialog();RECLASSIFY_TARGET={kind,id};const sel=$('#reclassifySelect');sel.innerHTML=CLASSIFICATION_CHOICES().map(([k,s])=>`<option value="${esc(k)}">${esc(s.label)}</option>`).join('');let current=null,title='';if(kind==='external'){const x=state.externalCandidates.find(x=>x.id===id);if(!x)return;current=x.classification||inferExternalProductionType(x);title=x.title||''}else if(kind==='doi'){const a=state.articles.find(x=>x.id===id),u=state.updates.find(x=>x.articleId===id);if(!a||!u)return;current=u.manualClassification||doiSuggestedClassification(u,a);title=a.title||''}else if(kind==='queue'){const q=state.queue.find(x=>x.id===id);if(!q)return;current=q.patch?.classification?.key?q.patch.classification:null;title=q.title||q.operation||''}if(current?.key&&[...sel.options].some(o=>o.value===current.key))sel.value=current.key;$('#reclassifyContext').textContent=title;$('#reclassifyCurrent').textContent=`Classificação atual: ${current?.label||'não identificada'}${current?.confidence!==undefined?' · confiança '+Math.round(current.confidence*100)+'%':''}`;$('#reclassifyDialog').showModal()}
function applyReclassification(){if(!RECLASSIFY_TARGET)return;const cls=manualClassificationFor($('#reclassifySelect').value),{kind,id}=RECLASSIFY_TARGET;if(kind==='external'){const x=state.externalCandidates.find(x=>x.id===id);if(x){x.manualClassification=cls;x.classification=cls}}else if(kind==='doi'){const u=state.updates.find(x=>x.articleId===id);if(u)u.manualClassification=cls}else if(kind==='queue'){const q=state.queue.find(x=>x.id===id);if(q){q.patch=q.patch||{};q.patch.classification=cls;if(q.evidence?.externalCandidateId||q.evidence?.externalKey)q.operation=cls.operation;else if(String(q.targetId||'').startsWith('art-')&&cls.key!=='ARTIGO')q.operation='RECLASSIFICAR_REGISTRO_REVISADO'}}save();state.assistedPackage=null;$('#reclassifyDialog').close();renderAll()}
ensureReclassifyDialog();$('#reclassifySave').onclick=applyReclassification;
function doiSuggestedClassification(u,a){if(u?.manualClassification?.key)return u.manualClassification;const c=u?.candidates?.[0]||{},raw=c.raw||{};return __inferProductionAutomatic({title:c.title||a?.title||'',year:c.year||a?.year||'',doi:c.doi||u?.doi||'',venue:(raw['container-title']||[])[0]||a?.journal||'',type:raw.type||'journal-article',raw})}
const __renderUpdatesReclassify=renderUpdates;
renderUpdates=function(){__renderUpdatesReclassify();const missing=state.articles.filter(a=>!a.doi),cards=[...document.querySelectorAll('#updateList>.source')];cards.forEach((card,i)=>{const a=missing[i],u=a&&state.updates.find(x=>x.articleId===a.id);if(!a||!u||u.status!=='found')return;const cls=doiSuggestedClassification(u,a),main=card.querySelector('div'),row=card.querySelector('.row');if(main&&!main.querySelector('.doi-type-badge')){const e=document.createElement('div');e.className='doi-type-badge';e.style.marginTop='7px';e.innerHTML=`<span class="badge neutral">Tipo sugerido: ${esc(cls.label)}</span>${u.manualClassification?'<span class="badge ok" style="margin-left:5px">reclassificado pelo usuário</span>':''}`;main.appendChild(e)}if(row&&!row.querySelector('.doi-reclassify')){const b=document.createElement('button');b.className='btn doi-reclassify';b.textContent='Reclassificar tipo';b.onclick=()=>openReclassify('doi',a.id);row.appendChild(b)}})};
const __approveDoiReclassify=approveDoi;
approveDoi=function(id){const a=state.articles.find(x=>x.id===id),u=state.updates.find(x=>x.articleId===id);if(!a||!u?.doi)return;const cls=doiSuggestedClassification(u,a);if(cls.key==='ARTIGO'){const before=state.queue.length;__approveDoiReclassify(id);const q=state.queue.slice(before).find(x=>x.targetId===id&&x.patch?.doi===u.doi)||state.queue.find(x=>x.targetId===id&&x.patch?.doi===u.doi);if(q){q.patch.classification=cls;q.evidence.classificationSource=u.manualClassification?'reclassificação do usuário':'Crossref'}}else{if(state.queue.some(q=>q.targetId===id&&q.evidence?.doiReclassification))return alert('Esta reclassificação já está na fila.');state.queue.push({id:crypto.randomUUID?crypto.randomUUID():'q'+Date.now(),operation:'RECLASSIFICAR_REGISTRO_REVISADO',targetId:id,title:a.title,patch:{doi:u.doi,year:a.year,venue:a.journal,classification:cls},evidence:{source:'Crossref + reclassificação do usuário',doiReclassification:true,retrievedAt:u.checkedAt||new Date().toISOString(),score:u.score},approvedAt:new Date().toISOString(),status:'pending'});save();renderAll()}};
const __renderExternalReclassify=renderExternal;
renderExternal=function(){__renderExternalReclassify();[...document.querySelectorAll('#externalList>.source')].forEach(card=>{const title=card.querySelector('strong')?.textContent||'',x=state.externalCandidates.find(c=>normalizeTitle(c.title||'')===normalizeTitle(title));if(!x)return;const row=card.querySelector('.row');if(row&&!row.querySelector('.external-reclassify')){const b=document.createElement('button');b.className='btn external-reclassify';b.textContent='Reclassificar tipo';b.onclick=()=>openReclassify('external',x.id);row.appendChild(b)}if(x.manualClassification&&!card.querySelector('.manual-classification-note')){const n=document.createElement('div');n.className='small manual-classification-note';n.style.marginTop='4px';n.textContent='Classificação ajustada manualmente pelo usuário.';card.querySelector('div')?.appendChild(n)}})};
function encodingDamageCount(s){return ((String(s||'').match(/�/g)||[]).length*5)+((String(s||'').match(/Ã|Â|â€|â€“|â€”/g)||[]).length)}
function damageComparableText(s){return normalizeTitle(String(s||'').replace(/�+/g,' ').replace(/^\s*\d+[.)-]?\s*/,''))}
function canonicalTitleForQueue(q){if(q.targetId){const a=state.articles.find(x=>x.id===q.targetId);if(a&&!encodingDamageCount(a.title))return a.title;const r=state.records.find(x=>x.id===q.targetId);if(r&&!encodingDamageCount(r.title))return r.title}const xid=q.evidence?.externalCandidateId,key=q.evidence?.externalKey;if(xid||key){const x=state.externalCandidates.find(x=>x.id===xid||x.key===key);if(x&&!encodingDamageCount(x.title))return x.title}const did=q.evidence?.documentId;if(did){const d=state.documents.find(x=>x.id===did);if(d?.fields?.title&&!encodingDamageCount(d.fields.title))return d.fields.title}if(!encodingDamageCount(q.title))return '';const damaged=damageComparableText(q.title),year=String(q.patch?.year||'');let best={score:0,title:''};[...state.records,...state.articles].forEach(x=>{if(!x.title||encodingDamageCount(x.title))return;let score=jaccard(damaged,damageComparableText(x.title));if(year&&String(x.year||'')===year)score+=.12;if(score>best.score)best={score,title:x.title}});return best.score>=.55?best.title:''}
function repairQueueEncoding(){let fixed=0;for(const q of state.queue){if(!encodingDamageCount(q.title))continue;const cleanTitle=canonicalTitleForQueue(q);if(cleanTitle&&cleanTitle!==q.title){q.title=normalizeDisplayText(cleanTitle);fixed++}}if(fixed){state.assistedPackage=null;save()}return fixed}
const __buildAssistedEncoding=buildAssistedPackage;
buildAssistedPackage=function(){repairQueueEncoding();return __buildAssistedEncoding()};
const __renderWorkflowEncoding=renderWorkflow;
renderWorkflow=function(){const had=Boolean(state.assistedPackage),fixed=repairQueueEncoding();if(fixed&&had)state.assistedPackage=__buildAssistedEncoding();__renderWorkflowEncoding();if(fixed){const m=$('#workflowMeta');if(m)m.textContent=(m.textContent?m.textContent+' · ':'')+`${fixed} título(s) recuperado(s) da fonte canônica`}};
function effectiveQueueType(q){const c=q.patch?.classification;if(c?.label)return c.label;if(typeof c==='string'&&typeof DOC_TYPES!=='undefined'&&DOC_TYPES[c])return DOC_TYPES[c];return queueTypeLabel(q)}
function queueGroupLabel(q){const c=q.patch?.classification?.category||'';if(c==='PRODUCAO_BIBLIOGRAFICA')return 'Produção bibliográfica';if(c==='PRODUCAO_TECNICA')return 'Produção técnica';if(c==='PROJETO')return 'Projetos';if(c==='FORMACAO')return 'Formação';if(q.evidence?.documentId)return 'Evidências documentais';return 'Outras operações'}
function ensureQueueDashboard(){const section=$('#queueList')?.closest('.section.card');if(!section||$('#queueDashboard'))return;const box=document.createElement('div');box.id='queueDashboard';box.innerHTML=`<div class="grid" id="queueMetrics" style="margin:12px 0"></div><div class="row" style="justify-content:space-between;margin:10px 0 14px"><strong>Fila ordenada por data</strong><select id="queueFilter" class="btn"><option value="">Todos os tipos</option><option value="Produção bibliográfica">Produção bibliográfica</option><option value="Produção técnica">Produção técnica</option><option value="Projetos">Projetos</option><option value="Formação">Formação</option><option value="Evidências documentais">Evidências documentais</option><option value="Outras operações">Outras operações</option></select></div>`;section.insertBefore(box,$('#queueList'));$('#queueFilter').onchange=()=>renderQueue()}
async function removeQueueItem(id){const q=state.queue.find(x=>x.id===id);if(!q||!confirm('Remover esta operação da fila?'))return;state.queue=state.queue.filter(x=>x.id!==id);if(q.evidence?.documentId){const d=state.documents.find(x=>x.id===q.evidence.documentId);if(d){d.queued=false;try{await dbPut(d)}catch{}}}state.assistedPackage=null;save();renderAll()}
renderQueue=function(){repairQueueEncoding();ensureQueueDashboard();$('#mQueue').textContent=state.queue.length;$('#exportQueue').disabled=!state.queue.length;$('#clearQueue').disabled=!state.queue.length;const filter=$('#queueFilter')?.value||'',all=[...state.queue].sort((a,b)=>queuePresentationDate(b).key-queuePresentationDate(a).key||(b.approvedAt||'').localeCompare(a.approvedAt||'')),rows=all.filter(q=>!filter||queueGroupLabel(q)===filter);const metrics=$('#queueMetrics');if(metrics){const bib=all.filter(q=>queueGroupLabel(q)==='Produção bibliográfica').length,tec=all.filter(q=>queueGroupLabel(q)==='Produção técnica').length,rev=all.filter(q=>String(q.operation||'').includes('REVISAR')||String(q.operation||'').includes('RECLASSIFICAR')).length;metrics.innerHTML=`<div class="card metric"><div class="n">${all.length}</div><div class="label">operações</div></div><div class="card metric"><div class="n">${bib}</div><div class="label">bibliográficas</div></div><div class="card metric"><div class="n">${tec}</div><div class="label">técnicas</div></div><div class="card metric"><div class="n">${rev}</div><div class="label">exigem revisão</div></div>`}if(!rows.length){$('#queueList').innerHTML='<div class="empty">A fila está vazia neste filtro.</div>';return}let lastYear='';$('#queueList').innerHTML=rows.map((q,i)=>{const dt=queuePresentationDate(q),year=dt.year||'Sem data',type=effectiveQueueType(q),review=String(q.operation||'').includes('REVISAR')||String(q.operation||'').includes('RECLASSIFICAR'),head=year!==lastYear?`<div class="section-head" style="margin:18px 0 8px"><h3>${esc(year)}</h3></div>`:'';lastYear=year;return `${head}<div class="doc-card"><div class="doc-head"><div class="doc-title"><strong>${i+1}. ${esc(q.title||q.operation)}</strong><div class="doc-meta"><span class="badge neutral">${esc(dt.label)}</span><span class="badge neutral">${esc(type)}</span><span class="badge ${review?'warn':'ok'}">${review?'revisar':'pronto'}</span></div></div><div class="doc-actions"><button class="btn" onclick="openReclassify('queue','${q.id}')">Reclassificar</button><button class="btn danger" onclick="removeQueueItem('${q.id}')">Remover</button></div></div><div class="small" style="margin-top:8px"><strong>Operação:</strong> ${esc(q.operation)}<br><strong>Fonte:</strong> ${esc(q.evidence?.source||'revisão do usuário')}${q.evidence?.documentName?' · '+esc(q.evidence.documentName):''}</div></div>`}).join('')};
repairQueueEncoding();renderAll();