const SUPABASE_URL='https://pxdrxyrbjfdrdjzjttif.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable__IRwahP2phSouaoGbsLlxg_44vdQaNN';
const CLOUD_STATE_KEYS=['cv','articles','records','relations','coverage','retrospective','identityProfile','decisions','assistedPackage','schemaMap','audit','updates','queue','settings'];
let cloudClient=null,cloudSession=null;
async function loadSupabaseClient(){if(cloudClient)return cloudClient;if(!window.supabase?.createClient){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js';s.onload=resolve;s.onerror=()=>reject(new Error('Não foi possível carregar o cliente Supabase.'));document.head.appendChild(s)})}cloudClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return cloudClient}
function cloudSnapshotPayload(){const payload={};for(const k of CLOUD_STATE_KEYS)payload[k]=state[k];return {schema:'lattes-assist.cloud-snapshot.v1',createdAt:new Date().toISOString(),appVersion:'1.7-beta',state:payload}}
function restoreCloudState(payload){if(!payload?.state)throw new Error('Snapshot remoto inválido.');for(const k of CLOUD_STATE_KEYS){if(Object.prototype.hasOwnProperty.call(payload.state,k))state[k]=payload.state[k]}save();persistParsed();renderAll()}
function cloudStatus(msg,kind=''){const el=$('#cloudStatus');if(!el)return;el.textContent=msg;el.dataset.kind=kind}
function cloudUserLabel(){return cloudSession?.user?.email||''}
function renderCloudUi(){const signed=Boolean(cloudSession?.user);$('#cloudSignedOut').style.display=signed?'none':'block';$('#cloudSignedIn').style.display=signed?'block':'none';$('#cloudUser').textContent=signed?cloudUserLabel():'';$('#cloudSave').disabled=!signed;$('#cloudLoad').disabled=!signed;$('#cloudLogout').disabled=!signed}
function ensureCloudUi(){const host=$('#sources');if(!host||$('#cloudLogin'))return;const card=document.createElement('div');card.className='section card';card.innerHTML=`<div class="section-head"><h3>Conta e sincronização <span class="badge warn">beta</span></h3><span class="small">Supabase Auth + RLS</span></div><div class="notice">A conta do Lattes Assist é independente da Plataforma Lattes/CNPq. Esta beta sincroniza análise curricular, auditorias, decisões, fila e configurações. Certificados e arquivos originais não são enviados à nuvem nesta etapa.</div><div id="cloudSignedOut"><div class="formgrid"><label>E-mail<input id="cloudEmail" type="email" autocomplete="email" placeholder="nome@exemplo.com"></label><label>Senha<input id="cloudPassword" type="password" autocomplete="current-password" minlength="8" placeholder="mínimo de 8 caracteres"></label></div><div class="row" style="margin-top:12px"><button class="btn primary" id="cloudLogin">Entrar</button><button class="btn" id="cloudSignup">Criar conta</button></div></div><div id="cloudSignedIn" style="display:none"><div class="source"><div><strong>Conta autenticada</strong><span class="small" id="cloudUser"></span></div><span class="badge ok">conectado</span></div><div class="row" style="margin-top:12px"><button class="btn primary" id="cloudSave">Salvar análise na nuvem</button><button class="btn" id="cloudLoad">Recuperar análise da nuvem</button><button class="btn" id="cloudLogout">Sair</button></div></div><div class="small" id="cloudStatus" style="margin-top:10px"></div>`;host.appendChild(card)}
async function cloudSignUp(){const email=clean($('#cloudEmail').value),password=$('#cloudPassword').value;if(!email||password.length<8)return cloudStatus('Informe e-mail e uma senha com pelo menos 8 caracteres.','error');cloudStatus('Criando conta…');try{const c=await loadSupabaseClient();const {data,error}=await c.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;cloudSession=data.session||null;if(data.session){cloudStatus('Conta criada e sessão iniciada.','ok')}else{cloudStatus('Conta criada. Verifique o e-mail para confirmar o cadastro antes de entrar.','ok')}renderCloudUi()}catch(e){cloudStatus('Não foi possível criar a conta: '+e.message,'error')}}
async function cloudSignIn(){const email=clean($('#cloudEmail').value),password=$('#cloudPassword').value;if(!email||!password)return cloudStatus('Informe e-mail e senha.','error');cloudStatus('Entrando…');try{const c=await loadSupabaseClient();const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;cloudSession=data.session;cloudStatus('Sessão iniciada.','ok');renderCloudUi()}catch(e){cloudStatus('Falha no login: '+e.message,'error')}}
async function cloudSignOut(){try{const c=await loadSupabaseClient();const {error}=await c.auth.signOut();if(error)throw error;cloudSession=null;cloudStatus('Sessão encerrada.','ok');renderCloudUi()}catch(e){cloudStatus('Não foi possível sair: '+e.message,'error')}}
async function saveCloudSnapshot(){if(!cloudSession?.user)return;cloudStatus('Salvando análise…');try{const c=await loadSupabaseClient(),payload=cloudSnapshotPayload();const {data:existing,error:readError}=await c.from('user_snapshots').select('id').eq('user_id',cloudSession.user.id).eq('label','Estado principal').maybeSingle();if(readError)throw readError;let error;if(existing?.id){({error}=await c.from('user_snapshots').update({payload,app_version:'1.7-beta',updated_at:new Date().toISOString()}).eq('id',existing.id))}else{({error}=await c.from('user_snapshots').insert({user_id:cloudSession.user.id,label:'Estado principal',payload,app_version:'1.7-beta'}))}if(error)throw error;cloudStatus('Análise sincronizada com sucesso. Arquivos originais permaneceram locais.','ok')}catch(e){cloudStatus('Falha ao salvar na nuvem: '+e.message,'error')}}
async function loadCloudSnapshot(){if(!cloudSession?.user)return;cloudStatus('Recuperando análise…');try{const c=await loadSupabaseClient();const {data,error}=await c.from('user_snapshots').select('payload,updated_at,app_version').eq('user_id',cloudSession.user.id).eq('label','Estado principal').maybeSingle();if(error)throw error;if(!data?.payload)return cloudStatus('Ainda não existe uma análise salva nesta conta.','warn');if(!confirm(`Substituir o estado curricular local pela análise salva na nuvem em ${new Date(data.updated_at).toLocaleString('pt-BR')}?\n\nCertificados e arquivos originais locais não serão apagados.`))return;restoreCloudState(data.payload);cloudStatus('Análise recuperada. Documentos locais foram preservados.','ok')}catch(e){cloudStatus('Falha ao recuperar a análise: '+e.message,'error')}}
async function initCloudAuth(){ensureCloudUi();try{const c=await loadSupabaseClient();const {data}=await c.auth.getSession();cloudSession=data.session||null;c.auth.onAuthStateChange((_event,session)=>{cloudSession=session;renderCloudUi()});renderCloudUi()}catch(e){cloudStatus('Sincronização indisponível: '+e.message,'error')}$('#cloudLogin')?.addEventListener('click',cloudSignIn);$('#cloudSignup')?.addEventListener('click',cloudSignUp);$('#cloudLogout')?.addEventListener('click',cloudSignOut);$('#cloudSave')?.addEventListener('click',saveCloudSnapshot);$('#cloudLoad')?.addEventListener('click',loadCloudSnapshot)}
initCloudAuth();