const EXTERNAL_CLOUD_STATE_KEYS=['cv','articles','records','relations','coverage','retrospective','externalCandidates','externalSources','identityProfile','decisions','assistedPackage','schemaMap','audit','updates','queue','settings'];

cloudSnapshotPayload=function(){const payload={};for(const k of EXTERNAL_CLOUD_STATE_KEYS)payload[k]=state[k];return {schema:'lattes-assist.cloud-snapshot.v1.1',createdAt:new Date().toISOString(),appVersion:'1.7-beta-external',state:payload}};
restoreCloudState=function(payload){if(!payload?.state)throw new Error('Snapshot remoto inválido.');for(const k of EXTERNAL_CLOUD_STATE_KEYS){if(Object.prototype.hasOwnProperty.call(payload.state,k))state[k]=payload.state[k]}save();persistParsed();renderAll();if(typeof renderExternal==='function')renderExternal()};

sectionForOperation=function(op,title=''){const s=normalizeTitle(op+' '+title);if(/criar artigo|criar livro|criar capitulo|criar trabalho evento|criar outra producao bibliografica|criar texto jornal revista/.test(s))return 'Produções > Produção bibliográfica';if(/criar software|criar producao tecnica|criar relatorio pesquisa|criar patente|criar atividade tecnica/.test(s))return 'Produções > Produção técnica';if(/revisar formacao titulacao/.test(s))return 'Formação acadêmica / titulação';if(s.includes('banca'))return 'Bancas';if(s.includes('orienta'))return 'Orientações';if(s.includes('evento'))return 'Eventos';if(s.includes('projeto'))return 'Projetos';if(s.includes('formacao'))return 'Formação complementar';if(s.includes('premio'))return 'Prêmios e títulos';if(s.includes('institucional')||s.includes('gestao'))return 'Atuação profissional';if(s.includes('tecnica'))return 'Produções > Produção técnica';if(s.includes('artigo')||s.includes('livro')||s.includes('capitulo')||s.includes('producao'))return 'Produções > Produção bibliográfica';return 'Revisar categoria no Lattes'};
workflowFields=function(q){const p=q.patch||{},fields=[];const add=(label,val)=>{if(val!==undefined&&val!==null&&String(val).trim()!=='')fields.push({label,value:val})};add('Título',q.title);add('Ano',p.year);add('DOI',p.doi);add('Periódico/Editora/Veículo',p.venue);add('Tipo na fonte',p.type);if(Array.isArray(p.authors)&&p.authors.length)add('Autores',p.authors.join('; '));if(p.classification){if(typeof p.classification==='object'){add('Tipo reconhecido',p.classification.label);add('Categoria Lattes',p.classification.category);add('Elemento sugerido',p.classification.subtype);if(typeof p.classification.confidence==='number')add('Confiança da classificação',Math.round(p.classification.confidence*100)+'%');if(Array.isArray(p.classification.reasons)&&p.classification.reasons.length)add('Razões da classificação',p.classification.reasons.join('; '))}else add('Classificação',p.classification)}if(p.fields){Object.entries(p.fields).forEach(([k,v])=>{if(Array.isArray(v)&&v.length)add(k,v.join('; '));else add(k,v)})}return fields.slice(0,24)};

const buildDecisionsBeforeExternalTypes=buildDecisions;
buildDecisions=function(){const out=buildDecisionsBeforeExternalTypes();for(const d of out){if(d.sourceType!=='external')continue;const x=state.externalCandidates.find(c=>c.id===d.externalId);if(!x)continue;const cls=x.classification||inferExternalProductionType(x);d.category=cls.label;d.productionType=cls;d.rationale=[...(d.rationale||[])];if(cls.key!=='OUTRO')d.rationale.push(`tipo reconhecido: ${cls.label} (${Math.round(cls.confidence*100)}%)`)}return out};

function updateSourceStatusCards(){const sources=$('#sources');if(!sources)return;const cards=[...sources.querySelectorAll('.source')];for(const card of cards){const strong=card.querySelector('strong');if(!strong)continue;const text=strong.textContent||'';const small=card.querySelector('.small');const badge=card.querySelector('.badge');if(text.includes('ORCID Public API')){if(small)small.textContent='Consulta de trabalhos públicos e peer reviews por conector autenticado no backend; requer credenciais ORCID Public API configuradas como secrets.';if(badge){badge.textContent='conector ativo';badge.className='badge warn'}}if(text.includes('Outras fontes')){if(small)small.textContent='OpenAlex e DataCite ativos na prospecção; Crossref complementa metadados bibliográficos. Zenodo direto permanece reservado a conector autenticado.';if(badge){badge.textContent='parcialmente ativo';badge.className='badge ok'}}}}
function autoEnableOrcid(){const input=$('#externalOrcid'),box=$('#useOrcid');if(!input||!box)return;const sync=()=>{const v=clean(input.value||state.settings.orcid||'').replace(/^https?:\/\/orcid\.org\//i,'');if(/^\d{4}-\d{4}-\d{4}-[\dX]{4}$/i.test(v))box.checked=true};sync();input.addEventListener('input',sync)}
function enhanceExternalProspectingUi(){updateSourceStatusCards();autoEnableOrcid();const config=document.querySelector('#external .section.card');if(config&&!document.getElementById('externalTypeLegend')){const note=document.createElement('div');note.id='externalTypeLegend';note.className='notice';note.style.marginTop='12px';note.innerHTML='<strong>Classificação automática:</strong> o tipo declarado pela fonte tem prioridade. Título e veículo funcionam apenas como sinais auxiliares. Tipos com confiança insuficiente permanecem em revisão manual.';config.appendChild(note)}}

enhanceExternalProspectingUi();