const BACKUP_SCHEMA='lattes-assist.backup.v1';
const BACKUP_STATE_KEYS=['cv','articles','records','relations','coverage','retrospective','externalCandidates','externalSources','identityProfile','decisions','assistedPackage','schemaMap','xsdInfo','rebuiltXml','rebuildReport','diffReport','semanticDiff','stableIdentityReport','audit','updates','queue','documents','settings'];

function bytesToBase64(bytes){let s='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)s+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(s)}
function base64ToBytes(s){const bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function blobToBackup(blob){if(!blob)return null;const bytes=new Uint8Array(await blob.arrayBuffer());return {type:blob.type||'application/octet-stream',size:blob.size,base64:bytesToBase64(bytes)}}
function backupToBlob(x){if(!x?.base64)return null;return new Blob([base64ToBytes(x.base64)],{type:x.type||'application/octet-stream'})}
function serializableState(){const out={};for(const k of BACKUP_STATE_KEYS)out[k]=state[k];return out}
function localStorageSnapshot(){const out={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('lattesAssist.'))out[k]=localStorage.getItem(k)}return out}
async function dbBackupSnapshot(){const docs=await dbAll(),files=[];for(const d of docs){const blob=await dbGetBlob(d.id);files.push({id:d.id,blob:await blobToBackup(blob)})}return {name:DB_NAME,version:DB_VERSION,documents:docs,files}}
function backupSummary(payload){const db=payload.indexedDB||{};const bytes=(db.files||[]).reduce((n,x)=>n+(x.blob?.size||0),0);return {documents:(db.documents||[]).length,files:(db.files||[]).filter(x=>x.blob).length,fileBytes:bytes,queue:(payload.state?.queue||[]).length,records:(payload.state?.records||[]).length,hasRawXml:Boolean(payload.session?.rawXml)}}
async function buildFullBackup(){return {schema:BACKUP_SCHEMA,appVersion:'1.6',createdAt:new Date().toISOString(),origin:location.origin+location.pathname,state:serializableState(),localStorage:localStorageSnapshot(),indexedDB:await dbBackupSnapshot(),session:{rawXml:state.runtime.rawXml||'',rawXsd:state.runtime.rawXsd||''}}}
async function deriveBackupKey(passphrase,salt){const enc=new TextEncoder();const base=await crypto.subtle.importKey('raw',enc.encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptBackup(payload,passphrase){const enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveBackupKey(passphrase,salt),plain=enc.encode(JSON.stringify(payload)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return {schema:'lattes-assist.backup.encrypted.v1',createdAt:payload.createdAt,kdf:{name:'PBKDF2',hash:'SHA-256',iterations:210000,salt:bytesToBase64(salt)},cipher:{name:'AES-GCM',iv:bytesToBase64(iv)},data:bytesToBase64(new Uint8Array(cipher))}}
async function decryptBackup(container,passphrase){if(container?.schema!=='lattes-assist.backup.encrypted.v1')return container;const salt=base64ToBytes(container.kdf.salt),iv=base64ToBytes(container.cipher.iv),key=await deriveBackupKey(passphrase,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,base64ToBytes(container.data));return JSON.parse(new TextDecoder().decode(plain))}
function downloadBackup(name,obj){const blob=new Blob([JSON.stringify(obj)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function exportFullBackup(){const btn=$('#backupExport');btn.disabled=true;$('#backupStatus').textContent='Preparando backup integral…';try{const payload=await buildFullBackup(),pass=clean($('#backupPassphrase').value);const out=pass?await encryptBackup(payload,pass):payload;const date=new Date().toISOString().slice(0,10);downloadBackup(`lattes-assist-backup-${date}${pass?'.encrypted':''}.json`,out);const s=backupSummary(payload);$('#backupStatus').textContent=`Backup criado: ${s.documents} documento(s), ${s.files} arquivo(s) original(is), ${fmtBytes(s.fileBytes)}.`;renderBackupInfo(payload)}catch(e){$('#backupStatus').textContent='Falha no backup: '+e.message}finally{btn.disabled=false}}
function validateBackupPayload(p){if(!p||p.schema!==BACKUP_SCHEMA)throw new Error('Arquivo não reconhecido como backup integral do Lattes Assist.');if(!p.state||!p.indexedDB)throw new Error('Backup incompleto: estado ou IndexedDB ausente.');return p}
async function clearEvidenceDb(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction([STORE,FILE_STORE],'readwrite');tx.objectStore(STORE).clear();tx.objectStore(FILE_STORE).clear();tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function restoreEvidenceDb(snapshot){await clearEvidenceDb();const docs=snapshot.documents||[],fileMap=new Map((snapshot.files||[]).map(x=>[x.id,x.blob]));for(const d of docs){const blob=backupToBlob(fileMap.get(d.id));await dbPut({...d,blob})}}
function restoreStateSnapshot(s){for(const k of BACKUP_STATE_KEYS){if(Object.prototype.hasOwnProperty.call(s,k))state[k]=s[k]}state.runtime.rawXml='';state.runtime.rawXsd=''}
async function restoreFullBackupFile(file){let container;try{container=JSON.parse(await file.text())}catch{throw new Error('O arquivo selecionado não contém JSON válido.')}let payload=container;if(container.schema==='lattes-assist.backup.encrypted.v1'){const pass=clean($('#backupPassphrase').value);if(!pass)throw new Error('Informe a senha usada para criptografar este backup.');try{payload=await decryptBackup(container,pass)}catch{throw new Error('Não foi possível descriptografar o backup. Verifique a senha.')}}validateBackupPayload(payload);const s=backupSummary(payload);if(!confirm(`Restaurar este backup substituirá os dados locais atuais.\n\n${s.documents} documento(s) · ${s.files} arquivo(s) · ${s.queue} operação(ões) na fila.\n\nContinuar?`))return;$('#backupStatus').textContent='Restaurando dados e documentos…';await restoreEvidenceDb(payload.indexedDB);Object.keys(localStorage).filter(k=>k.startsWith('lattesAssist.')).forEach(k=>localStorage.removeItem(k));Object.entries(payload.localStorage||{}).forEach(([k,v])=>localStorage.setItem(k,v));restoreStateSnapshot(payload.state||{});state.runtime.rawXml=payload.session?.rawXml||'';state.runtime.rawXsd=payload.session?.rawXsd||'';save();await loadDocuments();renderAll();renderBackupInfo(payload);$('#backupStatus').textContent='Restauração concluída. Os dados locais foram substituídos pelo backup.'}
function renderBackupInfo(payload=null){const p=payload,s=p?backupSummary(p):null;$('#backupLast').textContent=s?`${s.documents} docs · ${s.files} originais · ${fmtBytes(s.fileBytes)}`:'Nenhum backup carregado nesta sessão.';$('#backupCurrent').textContent=`${state.documents.length} documento(s) · ${state.queue.length} operação(ões) na fila · ${state.records.length} registro(s) curriculares`}
function initBackupRestore(){renderBackupInfo();$('#backupExport')?.addEventListener('click',exportFullBackup);$('#backupImport')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{await restoreFullBackupFile(f)}catch(err){$('#backupStatus').textContent='Falha na restauração: '+err.message}finally{e.target.value=''}})}
initBackupRestore();