function reconcileDocument(doc){
  const f=doc.fields||{},cat=categoryForDocument(doc.classification?.type);if(!cat)return {status:'not-comparable',label:'classificação ainda não comparável ao XML'};
  const candidates=state.records.filter(r=>r.category===cat);if(!candidates.length){if(!state.cv)return {status:'not-comparable',label:'importe o XML para comparar esta evidência'};return {status:'candidate-missing',label:'categoria não localizada no XML importado; revisar antes de criar registro',score:0,category:cat};}
  const scored=candidates.map(r=>({r,score:recordSimilarity(doc,r)})).sort((a,b)=>b.score-a.score);const best=scored[0];
  if(best?.score>=.72)return {status:'matched',label:'correspondência localizada no Lattes',recordId:best.r.id,articleId:best.r.subtype==='ARTIGO-PUBLICADO'?state.articles.find(a=>normalizeTitle(a.title)===normalizeTitle(best.r.title)&&a.year===best.r.year)?.id:null,score:best.score,title:best.r.title,category:cat,subtype:best.r.subtype};
  if(best?.score>=.48)return {status:'uncertain',label:'há registro semelhante, mas a correspondência é incerta',recordId:best.r.id,score:best.score,title:best.r.title,category:cat,subtype:best.r.subtype};
  const evidenceEnough=Boolean((f.title&&((f.years||[]).length||f.doi))||f.doi||(doc.reviewed&&doc.classification?.type!=='DOCUMENTO_GENERICO'));
  if(evidenceEnough)return {status:'candidate-missing',label:'não localizada entre os registros importados; candidata a ausência, requer revisão',score:best?.score||0,category:cat,nearest:best?.r?.title||''};
  return {status:'uncertain',label:'evidência insuficiente para afirmar presença ou ausência',score:best?.score||0,category:cat,nearest:best?.r?.title||''};
}
function makeDocRecord(file,hash,ext){const classification=classifyDocument(ext.text,file.name),fields=extractFields(ext.text);const rec={id:crypto.randomUUID?crypto.randomUUID():'doc-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:file.name,mime:file.type||'',size:file.size,sha256:hash,addedAt:new Date().toISOString(),text:ext.text||'',textLength:(ext.text||'').length,extraction:{method:ext.method,confidence:ext.confidence,pages:ext.pages||1,ocrPages:ext.ocrPages||0,warning:ext.warning||''},classification,fields,reviewed:false,queued:false};rec.reconciliation=reconcileDocument(rec);return rec}
async function processFiles(files){const arr=[...files];if(!arr.length)return;state.runtime.batchProcessed=0;state.runtime.batchDuplicates=0;for(let i=0;i<arr.length;i++){const file=arr[i];try{updateDocProgress('Preparando arquivo',i/arr.length*100,`${i+1} de ${arr.length} · ${file.name}`);const hash=await sha256(file);if(hash&&state.documents.some(d=>d.sha256===hash)){state.runtime.batchDuplicates++;continue}const ext=await extractFile(file);const rec=makeDocRecord(file,hash,ext);await dbPut({...rec,blob:file});state.documents.unshift(rec);state.runtime.batchProcessed++;renderAll()}catch(e){alert(`Não foi possível processar “${file.name}”: ${e.message}`)}}updateDocProgress('Concluído',100,`${arr.length} arquivo(s) analisado(s).`);hideDocProgress();renderAll()}
function docStatus(doc){if(doc.extraction?.warning)return '<span class="badge warn">revisar OCR</span>';if(doc.classification?.type==='DOCUMENTO_GENERICO')return '<span class="badge warn">classificar</span>';if(doc.reviewed)return '<span class="badge ok">revisado</span>';return '<span class="badge neutral">sugestão</span>'}
function fieldChips(f={}){const x=[];if(f.title)x.push(['título',f.title]);if(f.dates?.length)x.push(['data',f.dates.join(', ')]);else if(f.years?.length)x.push(['ano',f.years.join(', ')]);if(f.workload)x.push(['carga',f.workload]);if(f.doi)x.push(['DOI',f.doi]);if(f.issn)x.push(['ISSN',f.issn]);if(f.isbn)x.push(['ISBN',f.isbn]);if(f.beneficiary)x.push(['pessoa',f.beneficiary]);return x.slice(0,6).map(([a,b])=>`<span class="field"><strong>${esc(a)}:</strong> ${esc(b)}</span>`).join('')}
function renderDocuments(){const docs=state.documents;$('#dTotal').textContent=docs.length;$('#mDocs').textContent=docs.length;$('#dOcr').textContent=docs.filter(d=>(d.extraction?.ocrPages||0)>0).length;$('#dReview').textContent=docs.filter(d=>!d.reviewed&&(d.classification?.type==='DOCUMENTO_GENERICO'||d.extraction?.warning)).length;$('#dQueued').textContent=docs.filter(d=>d.queued).length;$('#dMatched').textContent=docs.filter(d=>d.reconciliation?.status==='matched').length;$('#dMissing').textContent=docs.filter(d=>d.reconciliation?.status==='candidate-missing').length;$('#dUncertain').textContent=docs.filter(d=>d.reconciliation?.status==='uncertain').length;$('#dBatch').textContent=state.runtime.batchProcessed||0;$('#dDupFiles').textContent=state.runtime.batchDuplicates||0;$('#docCount').textContent=docs.length?`${docs.length} documento(s)` : '';$('#exportEvidence').disabled=!docs.length;if(!docs.length){$('#documentList').innerHTML='<div class="empty">Nenhum documento processado.</div>';return}$('#documentList').innerHTML=docs.map(d=>`<div class="doc-card"><div class="doc-head"><div class="doc-title"><strong>${esc(d.name)}</strong><div class="doc-meta"><span class="badge neutral">${esc(d.classification?.label||'não classificado')}</span>${docStatus(d)}${d.extraction?.ocrPages?`<span class="badge ok">OCR ${d.extraction.ocrPages} pág.</span>`:''}</div><div class="small" style="margin-top:6px">${esc(d.extraction?.method||'')} · ${fmtBytes(d.size||0)}${d.extraction?.confidence?` · OCR ${Math.round(d.extraction.confidence)}%`:''} · classificação ${Math.round((d.classification?.confidence||0)*100)}%${d.sha256?` · SHA-256 <span class="mono">${esc(d.sha256.slice(0,12))}…</span>`:''}</div></div><div class="doc-actions"><button class="btn" onclick="openOriginal('${d.id}')">Original</button><button class="btn" onclick="editDocument('${d.id}')">Revisar</button><button class="btn primary" ${d.queued?'disabled':''} onclick="queueDocument('${d.id}')">${d.queued?'Na fila':'Adicionar à fila'}</button><button class="btn danger" onclick="removeDocument('${d.id}')">Excluir</button></div></div><div class="fields">${fieldChips(d.fields)}</div><div class="small" style="margin-top:8px"><strong>Reconciliação:</strong> ${esc(d.reconciliation?.label||'não realizada')}${d.reconciliation?.title?` · ${esc(d.reconciliation.title)}`:''}${d.reconciliation?.score?` · similaridade ${(d.reconciliation.score*100).toFixed(0)}%`:''}</div>${d.extraction?.warning?`<div class="notice" style="margin:10px 0 0">${esc(d.extraction.warning)}</div>`:''}<div class="text-preview">${esc((d.text||'').slice(0,650))}${(d.text||'').length>650?'…':''}</div></div>`).join('')}
async function openOriginal(id){const win=window.open('about:blank','_blank');const blob=await dbGetBlob(id);if(!blob){if(win)win.close();return alert('O arquivo original não está disponível neste dispositivo.')}const url=URL.createObjectURL(blob);if(win)win.location.href=url;else window.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}
function editDocument(id){const d=state.documents.find(x=>x.id===id);if(!d)return;state.runtime.editDoc=id;$('#docClassSelect').innerHTML=Object.entries(DOC_TYPES).map(([k,v])=>`<option value="${k}" ${k===d.classification?.type?'selected':''}>${esc(v)}</option>`).join('');$('#docTextEdit').value=d.text||'';$('#docEditDialog').showModal()}
async function saveDocEdit(){const id=state.runtime.editDoc,d=state.documents.find(x=>x.id===id);if(!d)return;d.text=$('#docTextEdit').value;d.textLength=d.text.length;const auto=classifyDocument(d.text,d.name),manual=$('#docClassSelect').value;d.classification={...auto,type:manual,label:DOC_TYPES[manual],manual:true,confidence:1};d.fields=extractFields(d.text);d.reviewed=true;d.reconciliation=reconcileDocument(d);await dbPut(d);$('#docEditDialog').close();renderAll()}
function operationForDoc(type){return {BANCA:'CRIAR_BANCA',EVENTO:'CRIAR_PARTICIPACAO_EVENTO',ORIENTACAO:'CRIAR_OU_ATUALIZAR_ORIENTACAO',FORMACAO:'CRIAR_FORMACAO_COMPLEMENTAR',PREMIO:'CRIAR_PREMIO',GESTAO:'CRIAR_ATIVIDADE_INSTITUCIONAL',PROJETO:'CRIAR_PROJETO',PRODUCAO_BIBLIOGRAFICA:'CRIAR_OU_ATUALIZAR_PRODUCAO',PARECER:'CRIAR_ATIVIDADE_TECNICA',DOCUMENTO_GENERICO:'REVISAR_EVIDENCIA_DOCUMENTAL'}[type]||'REVISAR_EVIDENCIA_DOCUMENTAL'}
