const SUPABASE_CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
let cloudClient=null,cloudUser=null;
async function initCloud(){
  const cfg=window.LATTES_ASSIST_SUPABASE;if(!cfg?.url||!cfg?.publishableKey)return;
  try{const mod=await import(SUPABASE_CDN);cloudClient=mod.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await cloudClient.auth.getSession();cloudUser=data.session?.user||null;cloudClient.auth.onAuthStateChange((_e,s)=>{cloudUser=s?.user||null;renderCloudAccount()});ensureCloudUi();renderCloudAccount()}catch(e){console.warn('Supabase indisponível',e)}
}
function ensureCloudUi(){if($('#cloudAccountCard'))return;const host=$('#sources')||document.querySelector('.panel.active')||document.body;const card=document.createElement('div');card.id='cloudAccountCard';card.className='section card';card.innerHTML=`<div class="section-head"><h3>Conta e sincronização</h3><span class="small" id="cloudStatus">modo local</span></div><div id="cloudSignedOut"><div class="formgrid"><label>E-mail<input id="cloudEmail" type="email" autocomplete="email"></label><label>Senha<input id="cloudPassword" type="password" autocomplete="current-password"></label></div><div class="row" style="margin-top:12px"><button class="btn primary" id="cloudLogin">Entrar</button><button class="btn" id="cloudSignup">Criar conta</button></div></div><div id="cloudSignedIn" style="display:none"><p class="small">Conectado como <strong id="cloudUserEmail"></strong>. A senha é gerida pelo serviço de autenticação e não é armazenada pelo Lattes Assist.</p><div class="row"><button class="btn primary" id="cloudSave">Salvar análise na nuvem</button><button class="btn" id="cloudLoad">Carregar análise salva</button><button class="btn" id="cloudLogout">Sair</button></div></div><div class="small" id="cloudMessage" style="margin-top:10px"></div>`;host.appendChild(card);$('#cloudLogin').onclick=cloudSignIn;$('#cloudSignup').onclick=cloudSignUp;$('#cloudLogout').onclick=cloudSignOut;$('#cloudSave').onclick=cloudSaveSnapshot;$('#cloudLoad').onclick=cloudLoadSnapshot}
function renderCloudAccount(){if(!$('#cloudAccountCard'))return;$('#cloudSignedOut').style.display=cloudUser?'none':'';$('#cloudSignedIn').style.display=cloudUser?'':'none';$('#cloudStatus').textContent=cloudUser?'sincronização disponível':'modo local';if(cloudUser)$('#cloudUserEmail').textContent=cloudUser.email||cloudUser.id}
function cloudCredentials(){return {email:clean($('#cloudEmail')?.value),password:String($('#cloudPassword')?.value||'')}}
async function cloudSignUp(){const {email,password}=cloudCredentials();if(!email||password.length<8)return $('#cloudMessage').textContent='Informe um e-mail válido e uma senha com pelo menos 8 caracteres.';const {error}=await cloudClient.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});$('#cloudMessage').textContent=error?error.message:'Conta criada. Verifique seu e-mail se a confirmação estiver habilitada.'}
async function cloudSignIn(){const {email,password}=cloudCredentials();const {error}=await cloudClient.auth.signInWithPassword({email,password});$('#cloudMessage').textContent=error?error.message:'Login realizado.'}
async function cloudSignOut(){await cloudClient.auth.signOut();$('#cloudMessage').textContent='Sessão encerrada.'}
async function cloudSaveSnapshot(){if(!cloudUser)return;$('#cloudMessage').textContent='Preparando estado sincronizado…';try{const payload=await buildFullBackup();payload.indexedDB.files=[];payload.session.rawXml='';payload.session.rawXsd='';const {error}=await cloudClient.from('user_snapshots').upsert({user_id:cloudUser.id,label:'Estado principal',app_version:'1.7-beta',payload,updated_at:new Date().toISOString()},{onConflict:'user_id,label'});if(error)throw error;$('#cloudMessage').textContent='Análise sincronizada. Arquivos originais e XML bruto permaneceram somente neste dispositivo.'}catch(e){$('#cloudMessage').textContent='Falha ao sincronizar: '+e.message}}
async function cloudLoadSnapshot(){if(!cloudUser)return;if(!confirm('Carregar a análise salva na nuvem e substituir o estado local atual? Recomenda-se criar um backup local antes.'))return;try{const {data,error}=await cloudClient.from('user_snapshots').select('payload,updated_at').eq('user_id',cloudUser.id).eq('label','Estado principal').maybeSingle();if(error)throw error;if(!data?.payload)return $('#cloudMessage').textContent='Nenhuma análise sincronizada encontrada.';const p=validateBackupPayload(data.payload);for(const [k,v] of Object.entries(p.state||{})){if(k!=='documents'&&k in state)state[k]=v}for(const [k,v] of Object.entries(p.localStorage||{}))localStorage.setItem(k,v);save();persistParsed();renderAll();$('#cloudMessage').textContent='Estado sincronizado carregado. Documentos locais existentes foram preservados.'}catch(e){$('#cloudMessage').textContent='Falha ao carregar: '+e.message}}
setTimeout(initCloud,0);
