const PRESENTATION_MONTHS={janeiro:1,fevereiro:2,marco:3,março:3,abril:4,maio:5,junho:6,julho:7,agosto:8,setembro:9,outubro:10,novembro:11,dezembro:12};
function presentationDate(y,m=0,d=0){y=Number(y)||0;m=Number(m)||0;d=Number(d)||0;if(!y)return {key:0,label:'Data não informada',year:''};const key=y*10000+m*100+d;const label=d&&m?`${String(d).padStart(2,'0')}/${String(m).padStart(2,'0')}/${y}`:m?`${String(m).padStart(2,'0')}/${y}`:String(y);return {key,label,year:String(y)}}
function presentationDateFromString(v){const s=clean(v);if(!s)return presentationDate(0);let m=s.match(/\b((?:19|20)\d{2})-(\d{1,2})-(\d{1,2})\b/);if(m)return presentationDate(m[1],m[2],m[3]);m=s.match(/\b(\d{1,2})[\/.-](\d{1,2})[\/.-]((?:19|20)\d{2})\b/);if(m)return presentationDate(m[3],m[2],m[1]);m=s.match(/\b((?:19|20)\d{2})\b/);return m?presentationDate(m[1]):presentationDate(0)}
function presentationDatesFromText(text){const s=String(text||''),out=[];for(const m of s.matchAll(/\b(\d{1,2})[\/.-](\d{1,2})[\/.-]((?:19|20)\d{2})\b/g))out.push(presentationDate(m[3],m[2],m[1]));const monthNames=Object.keys(PRESENTATION_MONTHS).join('|');const re=new RegExp(`\\b(\\d{1,2})\\s+de\\s+(${monthNames})\\s+de\\s+((?:19|20)\\d{2})\\b`,'gi');for(const m of s.matchAll(re))out.push(presentationDate(m[3],PRESENTATION_MONTHS[m[2].toLowerCase()],m[1]));return out}
function bestPresentationDate(xs){return (xs||[]).filter(x=>x?.key).sort((a,b)=>b.key-a.key)[0]||presentationDate(0)}
function documentPresentationDate(d){const exact=[...(d.fields?.dates||[]).map(presentationDateFromString),...presentationDatesFromText(d.text||'')];if(exact.length)return bestPresentationDate(exact);const years=(d.fields?.years||[]).map(y=>presentationDate(y));return bestPresentationDate(years)}
function recordPresentationDate(r){return presentationDateFromString(r.date||r.year||'')}
function articlePresentationDate(a){return presentationDateFromString(a.date||a.year||'')}
function rawExternalDates(raw){if(!raw||typeof raw!=='object')return [];const out=[];if(raw.publication_date)out.push(presentationDateFromString(raw.publication_date));for(const k of ['published-print','published-online','published','issued','created']){const p=raw[k]?.['date-parts']?.[0];if(p?.[0])out.push(presentationDate(p[0],p[1],p[2]))}const a=raw.attributes||{};for(const d of a.dates||[]){if(/published|issued/i.test(d.dateType||''))out.push(presentationDateFromString(d.date))}if(a.publicationYear)out.push(presentationDate(a.publicationYear));for(const k of ['publication-date','completion-date']){const p=raw[k];const y=p?.year?.value,m=p?.month?.value,d=p?.day?.value;if(y)out.push(presentationDate(y,m,d))}return out}
function externalPresentationDate(x){let xs=[presentationDateFromString(x.date||''),presentationDateFromString(x.year||''),...rawExternalDates(x.raw)];for(const raw of Object.values(x.rawBySource||{}))xs=xs.concat(rawExternalDates(raw));return bestPresentationDate(xs)}
function queuePresentationDate(q){return presentationDateFromString(q.patch?.date||q.patch?.year||'')}
function queueTypeLabel(q){return q.patch?.classification?.label||({CRIAR_ARTIGO:'Artigo em periódico',CRIAR_LIVRO:'Livro publicado/organizado',CRIAR_CAPITULO_LIVRO:'Capítulo de livro',CRIAR_TRABALHO_EVENTO:'Trabalho em evento',CRIAR_SOFTWARE:'Software',CRIAR_RELATORIO_PESQUISA:'Relatório / nota técnica',CRIAR_PATENTE:'Patente',CRIAR_PROJETO:'Projeto',CRIAR_ATIVIDADE_TECNICA:'Produção técnica'}[q.operation]||q.patch?.classification||q.operation||'Tipo não identificado')}
function addPresentationMeta(card,info,type){if(!card)return;let host=card.querySelector('.doc-title')||card.firstElementChild||card;if(!host)return;let el=host.querySelector('.presentation-meta');if(!el){el=document.createElement('div');el.className='doc-meta presentation-meta';el.style.marginTop='5px';host.appendChild(el)}const bits=[`<span class="badge neutral">Data: ${esc(info?.label||'não informada')}</span>`];if(type&&!card.textContent.includes(type))bits.push(`<span class="badge neutral">Tipo: ${esc(type)}</span>`);el.innerHTML=bits.join(' ')}
const __renderDocumentsChronological=renderDocuments;
renderDocuments=function(){state.documents.sort((a,b)=>documentPresentationDate(b).key-documentPresentationDate(a).key||(b.addedAt||'').localeCompare(a.addedAt||''));__renderDocumentsChronological();[...document.querySelectorAll('#documentList>.doc-card')].forEach((card,i)=>{const d=state.documents[i];if(d)addPresentationMeta(card,documentPresentationDate(d),d.classification?.label||'Documento acadêmico')})};
const __renderExternalChronological=renderExternal;
renderExternal=function(){__renderExternalChronological();const box=$('#externalList');if(!box||!state.externalCandidates.length)return;const cards=[...box.children],current=[...state.externalCandidates],pairs=current.map((x,i)=>({x,card:cards[i]}));pairs.sort((a,b)=>externalPresentationDate(b.x).key-externalPresentationDate(a.x).key||(b.x.year||'').localeCompare(a.x.year||''));pairs.forEach(({x,card})=>{addPresentationMeta(card,externalPresentationDate(x),x.classification?.label||inferExternalProductionType(x).label);box.appendChild(card)});state.externalCandidates=pairs.map(p=>p.x)};
const __buildRetrospectiveChronological=buildRetrospective;
buildRetrospective=function(){__buildRetrospectiveChronological();state.retrospective.sort((a,b)=>presentationDateFromString(b.year||'').key-presentationDateFromString(a.year||'').key);return state.retrospective};
const __renderQueueChronological=renderQueue;
renderQueue=function(){__renderQueueChronological();const box=$('#queueList');if(!box||!state.queue.length)return;const cards=[...box.children],pairs=state.queue.map((q,i)=>({q,card:cards[i]}));pairs.sort((a,b)=>queuePresentationDate(b.q).key-queuePresentationDate(a.q).key||(b.q.approvedAt||'').localeCompare(a.q.approvedAt||''));pairs.forEach(({q,card})=>{addPresentationMeta(card,queuePresentationDate(q),queueTypeLabel(q));box.appendChild(card)})};
function decisionPresentationDate(d){if(d.externalId){const x=state.externalCandidates.find(x=>x.id===d.externalId);if(x)return externalPresentationDate(x)}if(d.documentId){const x=state.documents.find(x=>x.id===d.documentId);if(x)return documentPresentationDate(x)}if(d.lattesRecordId){const a=state.articles.find(x=>x.id===d.lattesRecordId);if(a)return articlePresentationDate(a);const r=state.records.find(x=>x.id===d.lattesRecordId);if(r)return recordPresentationDate(r)}return presentationDate(0)}
function decisionTypeLabel(d){if(d.externalId){const x=state.externalCandidates.find(x=>x.id===d.externalId);if(x)return x.classification?.label||inferExternalProductionType(x).label}if(d.documentId){const x=state.documents.find(x=>x.id===d.documentId);if(x)return x.classification?.label||'Documento acadêmico'}if(String(d.lattesRecordId||'').startsWith('art-'))return 'Artigo em periódico';const r=state.records.find(x=>x.id===d.lattesRecordId);return r?.subtypeLabel||d.category||'Tipo não identificado'}
const __renderDecisionsChronological=renderDecisions;
renderDecisions=function(){__renderDecisionsChronological();const box=$('#decisionList');if(!box||!state.decisions.length)return;const f=state.runtime.decisionFilter||'',current=state.decisions.filter(d=>!f||d.recommendation===f).sort((a,b)=>b.confidence-a.confidence),cards=[...box.children];if(cards.length!==current.length)return;const pairs=current.map((d,i)=>({d,card:cards[i]})).sort((a,b)=>decisionPresentationDate(b.d).key-decisionPresentationDate(a.d).key||b.d.confidence-a.d.confidence);pairs.forEach(({d,card})=>{addPresentationMeta(card,decisionPresentationDate(d),decisionTypeLabel(d));box.appendChild(card)})};
const __renderAllPresentation=renderAll;
renderAll=function(){__renderAllPresentation();const articleTable=$('#articleBody')?.closest('table'),recordTable=$('#recordBody')?.closest('table');if(articleTable?.tHead?.rows?.[0]?.cells?.[0])articleTable.tHead.rows[0].cells[0].textContent='Data/Ano';if(recordTable?.tHead?.rows?.[0]?.cells?.[0])recordTable.tHead.rows[0].cells[0].textContent='Data/Ano';const arts=[...state.articles].sort((a,b)=>articlePresentationDate(b).key-articlePresentationDate(a).key);[...document.querySelectorAll('#articleBody>tr')].forEach((tr,i)=>{const a=arts[i],cell=tr.querySelector('.titlecell');if(a&&cell&&!cell.querySelector('.presentation-article-type')){const x=document.createElement('div');x.className='doc-meta presentation-article-type';x.style.marginTop='5px';x.innerHTML='<span class="badge neutral">Tipo: Artigo em periódico</span>';cell.appendChild(x)}})};
renderAll();